// Carpentry tools: wood joinery, project templates, and material calculations

import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { z } from "zod";
import { client } from "../cncjs-client.js";
import { writeFileSync } from "fs";

function text(s: string) {
  return { content: [{ type: "text" as const, text: s }] };
}

function json(obj: unknown) {
  return text(JSON.stringify(obj, null, 2));
}

function err(s: string) {
  return { content: [{ type: "text" as const, text: s }], isError: true };
}

// ── Constants ──────────────────────────────────────────

const SAFE_Z = 5; // mm above work surface for rapids

// Wood material presets: feedrate (mm/min), spindleSpeed (RPM), stepDown (mm)
const WOOD_PRESETS: Record<string, { feedrate: number; spindleSpeed: number; stepDown: number; description: string }> = {
  pine: { feedrate: 1500, spindleSpeed: 18000, stepDown: 3, description: "Soft, easy to machine, common for framing and basic projects" },
  oak: { feedrate: 800, spindleSpeed: 16000, stepDown: 2, description: "Hard, durable, great for furniture and cabinetry" },
  walnut: { feedrate: 900, spindleSpeed: 16000, stepDown: 2.5, description: "Medium-hard, beautiful grain, premium furniture wood" },
  maple: { feedrate: 700, spindleSpeed: 16000, stepDown: 2, description: "Very hard, smooth finish, ideal for cutting boards and countertops" },
  cherry: { feedrate: 1000, spindleSpeed: 17000, stepDown: 2.5, description: "Medium-hard, ages beautifully, classic furniture wood" },
  birch: { feedrate: 1100, spindleSpeed: 17000, stepDown: 2.5, description: "Hard, fine grain, good for plywood and cabinetry" },
  cedar: { feedrate: 1600, spindleSpeed: 18000, stepDown: 3, description: "Soft, rot-resistant, ideal for outdoor projects" },
  plywood: { feedrate: 1200, spindleSpeed: 18000, stepDown: 3, description: "Layered sheet good, versatile for cabinetry and shelving" },
  mdf: { feedrate: 1400, spindleSpeed: 18000, stepDown: 3, description: "Medium-density fiberboard, smooth surface, good for painted projects" },
  bamboo: { feedrate: 900, spindleSpeed: 16000, stepDown: 2, description: "Hard, sustainable, good for cutting boards and decorative work" },
};

// ── G-code helpers ──────────────────────────────────────

function gcodeHeader(spindleSpeed: number): string[] {
  return [
    "; Generated by cncjs-mcp (carpentry module)",
    "G90 G21 ; Absolute positioning, millimeters",
    "G17 ; XY plane",
    `G0 Z${SAFE_Z} ; Retract to safe height`,
    `M3 S${spindleSpeed} ; Spindle on CW`,
    "G4 P2 ; Dwell 2s for spindle to reach speed",
  ];
}

function gcodeFooter(): string[] {
  return [
    `G0 Z${SAFE_Z} ; Retract to safe height`,
    "M5 ; Spindle off",
    "G0 X0 Y0 ; Return to origin",
    "M2 ; Program end",
  ];
}

export function registerCarpentryTools(server: McpServer): void {
  // ── generate_finger_joint ──────────────────────────────────

  server.tool(
    "generate_finger_joint",
    "Generate G-code for finger (box) joints along a board edge. Creates interlocking rectangular tabs for strong wood-to-wood joints without fasteners.",
    {
      boardLength: z.number().positive().describe("Length of the board edge to joint (mm)"),
      boardThickness: z.number().positive().describe("Thickness of the mating board — sets finger depth (mm)"),
      fingerWidth: z.number().positive().describe("Width of each finger/tab (mm)"),
      fingerCount: z.number().int().positive().optional().describe("Number of fingers (auto-calculated from boardLength/fingerWidth if omitted)"),
      startX: z.number().default(0).describe("Starting X position (mm)"),
      startY: z.number().default(0).describe("Starting Y position (mm)"),
      toolDiameter: z.number().positive().describe("End mill diameter (mm)"),
      wood: z.enum(["pine", "oak", "walnut", "maple", "cherry", "birch", "cedar", "plywood", "mdf", "bamboo"]).default("pine").describe("Wood type for automatic feed/speed selection"),
      feedrate: z.number().positive().optional().describe("Override cutting feed rate (mm/min)"),
      spindleSpeed: z.number().positive().optional().describe("Override spindle speed (RPM)"),
      autoLoad: z.boolean().default(true).describe("Automatically load into CNCjs (default true)"),
    },
    async (params) => {
      try {
        const { boardLength, boardThickness, fingerWidth, startX, startY, toolDiameter, wood, autoLoad } = params;
        const preset = WOOD_PRESETS[wood];
        const feedrate = params.feedrate ?? preset.feedrate;
        const spindleSpeed = params.spindleSpeed ?? preset.spindleSpeed;
        const stepDown = preset.stepDown;

        const count = params.fingerCount ?? Math.floor(boardLength / fingerWidth);
        if (count < 1) return err("Board length too short for the given finger width.");

        const actualFingerWidth = boardLength / count;
        const toolRadius = toolDiameter / 2;

        if (actualFingerWidth <= toolDiameter) {
          return err(`Finger width (${actualFingerWidth.toFixed(1)}mm) must be greater than tool diameter (${toolDiameter}mm).`);
        }

        const gcode: string[] = [...gcodeHeader(spindleSpeed)];
        gcode.push(`; Finger joint: ${count} fingers, ${actualFingerWidth.toFixed(1)}mm wide, ${boardThickness}mm deep`);
        gcode.push(`; Wood: ${wood} (${preset.description})`);

        // Cut every other slot (the "notches" between fingers)
        for (let i = 0; i < count; i += 2) {
          const slotX = startX + i * actualFingerWidth;
          const slotXEnd = slotX + actualFingerWidth;
          const pocketLeft = slotX + toolRadius;
          const pocketRight = slotXEnd - toolRadius;

          if (pocketRight <= pocketLeft) continue;

          let currentDepth = 0;
          while (currentDepth < boardThickness) {
            currentDepth = Math.min(currentDepth + stepDown, boardThickness);

            // Rapid to start of slot
            gcode.push(`G0 X${pocketLeft.toFixed(3)} Y${startY.toFixed(3)}`);
            gcode.push(`G1 Z${(-currentDepth).toFixed(3)} F${Math.round(feedrate / 3)} ; Plunge`);

            // Cut across slot width
            gcode.push(`G1 X${pocketRight.toFixed(3)} F${feedrate}`);

            // Step over in Y and cut back
            let y = startY;
            const stepOver = toolDiameter * 0.4;
            let leftToRight = false;
            while (y < startY + boardThickness) {
              y = Math.min(y + stepOver, startY + boardThickness);
              gcode.push(`G1 Y${y.toFixed(3)} F${feedrate}`);
              if (leftToRight) {
                gcode.push(`G1 X${pocketRight.toFixed(3)} F${feedrate}`);
              } else {
                gcode.push(`G1 X${pocketLeft.toFixed(3)} F${feedrate}`);
              }
              leftToRight = !leftToRight;
            }

            gcode.push(`G0 Z${SAFE_Z}`);
          }
        }

        gcode.push(...gcodeFooter());
        const gcodeStr = gcode.join("\n");

        if (autoLoad) {
          const name = `finger_joint_${wood}_${Date.now()}.nc`;
          client.loadGcode(name, gcodeStr);
          return text(`Finger joint G-code generated and loaded (${count} fingers, ${wood}, ${gcode.length} lines).\nUse start_job to execute.\n\nPreview:\n${gcodeStr}`);
        }
        return text(`Finger joint G-code generated (${count} fingers, ${gcode.length} lines):\n\n${gcodeStr}`);
      } catch (e: any) {
        return err(e.message);
      }
    }
  );

  // ── generate_dado_joint ──────────────────────────────────

  server.tool(
    "generate_dado_joint",
    "Generate G-code for a dado (groove/channel) joint. Creates a rectangular channel in one board to receive another board edge, commonly used for shelving and cabinetry.",
    {
      dadoLength: z.number().positive().describe("Length of the dado channel (mm)"),
      dadoWidth: z.number().positive().describe("Width of the dado — should match mating board thickness (mm)"),
      dadoDepth: z.number().positive().describe("Depth of the dado — typically 1/3 to 1/2 board thickness (mm)"),
      startX: z.number().default(0).describe("Starting X position (mm)"),
      startY: z.number().default(0).describe("Starting Y position (mm)"),
      orientation: z.enum(["horizontal", "vertical"]).default("horizontal").describe("Dado direction relative to board"),
      toolDiameter: z.number().positive().describe("End mill diameter (mm)"),
      wood: z.enum(["pine", "oak", "walnut", "maple", "cherry", "birch", "cedar", "plywood", "mdf", "bamboo"]).default("pine").describe("Wood type for automatic feed/speed selection"),
      feedrate: z.number().positive().optional().describe("Override cutting feed rate (mm/min)"),
      spindleSpeed: z.number().positive().optional().describe("Override spindle speed (RPM)"),
      autoLoad: z.boolean().default(true).describe("Automatically load into CNCjs (default true)"),
    },
    async (params) => {
      try {
        const { dadoLength, dadoWidth, dadoDepth, startX, startY, orientation, toolDiameter, wood, autoLoad } = params;
        const preset = WOOD_PRESETS[wood];
        const feedrate = params.feedrate ?? preset.feedrate;
        const spindleSpeed = params.spindleSpeed ?? preset.spindleSpeed;
        const stepDown = preset.stepDown;

        if (dadoWidth < toolDiameter) {
          return err(`Dado width (${dadoWidth}mm) must be at least tool diameter (${toolDiameter}mm). Use a smaller bit.`);
        }

        const gcode: string[] = [...gcodeHeader(spindleSpeed)];
        gcode.push(`; Dado joint: ${dadoLength}x${dadoWidth}mm, ${dadoDepth}mm deep, ${orientation}`);
        gcode.push(`; Wood: ${wood} (${preset.description})`);

        const toolRadius = toolDiameter / 2;
        const stepOver = toolDiameter * 0.4;

        let currentDepth = 0;
        while (currentDepth < dadoDepth) {
          currentDepth = Math.min(currentDepth + stepDown, dadoDepth);

          if (orientation === "horizontal") {
            // Raster along X, step over in Y
            let y = startY + toolRadius;
            const yEnd = startY + dadoWidth - toolRadius;
            let leftToRight = true;

            gcode.push(`G0 X${startX.toFixed(3)} Y${y.toFixed(3)}`);
            gcode.push(`G1 Z${(-currentDepth).toFixed(3)} F${Math.round(feedrate / 3)}`);

            while (y <= yEnd + 0.001) {
              if (leftToRight) {
                gcode.push(`G1 X${(startX + dadoLength).toFixed(3)} Y${y.toFixed(3)} F${feedrate}`);
              } else {
                gcode.push(`G1 X${startX.toFixed(3)} Y${y.toFixed(3)} F${feedrate}`);
              }
              y = Math.min(y + stepOver, yEnd + 0.001);
              if (y <= yEnd + 0.001) {
                gcode.push(`G1 Y${Math.min(y, yEnd).toFixed(3)} F${feedrate}`);
              }
              leftToRight = !leftToRight;
            }
          } else {
            // Raster along Y, step over in X
            let x = startX + toolRadius;
            const xEnd = startX + dadoWidth - toolRadius;
            let bottomToTop = true;

            gcode.push(`G0 X${x.toFixed(3)} Y${startY.toFixed(3)}`);
            gcode.push(`G1 Z${(-currentDepth).toFixed(3)} F${Math.round(feedrate / 3)}`);

            while (x <= xEnd + 0.001) {
              if (bottomToTop) {
                gcode.push(`G1 X${x.toFixed(3)} Y${(startY + dadoLength).toFixed(3)} F${feedrate}`);
              } else {
                gcode.push(`G1 X${x.toFixed(3)} Y${startY.toFixed(3)} F${feedrate}`);
              }
              x = Math.min(x + stepOver, xEnd + 0.001);
              if (x <= xEnd + 0.001) {
                gcode.push(`G1 X${Math.min(x, xEnd).toFixed(3)} F${feedrate}`);
              }
              bottomToTop = !bottomToTop;
            }
          }

          gcode.push(`G0 Z${SAFE_Z}`);
        }

        gcode.push(...gcodeFooter());
        const gcodeStr = gcode.join("\n");

        if (autoLoad) {
          const name = `dado_${orientation}_${wood}_${Date.now()}.nc`;
          client.loadGcode(name, gcodeStr);
          return text(`Dado joint G-code generated and loaded (${dadoLength}x${dadoWidth}mm, ${wood}, ${gcode.length} lines).\nUse start_job to execute.\n\nPreview:\n${gcodeStr}`);
        }
        return text(`Dado joint G-code generated (${gcode.length} lines):\n\n${gcodeStr}`);
      } catch (e: any) {
        return err(e.message);
      }
    }
  );

  // ── generate_rabbet_joint ──────────────────────────────────

  server.tool(
    "generate_rabbet_joint",
    "Generate G-code for a rabbet (rebate) joint. Cuts a step/ledge along a board edge for overlapping joints, commonly used in drawer and cabinet construction.",
    {
      rabbetLength: z.number().positive().describe("Length along the board edge (mm)"),
      rabbetWidth: z.number().positive().describe("Width of the rabbet step — typically matches mating board thickness (mm)"),
      rabbetDepth: z.number().positive().describe("Depth of the rabbet — typically 1/2 to 2/3 board thickness (mm)"),
      startX: z.number().default(0).describe("Starting X position (mm)"),
      startY: z.number().default(0).describe("Starting Y position (mm)"),
      edge: z.enum(["top", "bottom", "left", "right"]).default("right").describe("Which edge of the board to rabbet"),
      toolDiameter: z.number().positive().describe("End mill diameter (mm)"),
      wood: z.enum(["pine", "oak", "walnut", "maple", "cherry", "birch", "cedar", "plywood", "mdf", "bamboo"]).default("pine").describe("Wood type for automatic feed/speed selection"),
      feedrate: z.number().positive().optional().describe("Override cutting feed rate (mm/min)"),
      spindleSpeed: z.number().positive().optional().describe("Override spindle speed (RPM)"),
      autoLoad: z.boolean().default(true).describe("Automatically load into CNCjs (default true)"),
    },
    async (params) => {
      try {
        const { rabbetLength, rabbetWidth, rabbetDepth, startX, startY, edge, toolDiameter, wood, autoLoad } = params;
        const preset = WOOD_PRESETS[wood];
        const feedrate = params.feedrate ?? preset.feedrate;
        const spindleSpeed = params.spindleSpeed ?? preset.spindleSpeed;
        const stepDown = preset.stepDown;

        const gcode: string[] = [...gcodeHeader(spindleSpeed)];
        gcode.push(`; Rabbet joint: ${rabbetLength}mm long, ${rabbetWidth}x${rabbetDepth}mm step, edge=${edge}`);
        gcode.push(`; Wood: ${wood} (${preset.description})`);

        const toolRadius = toolDiameter / 2;
        const stepOver = toolDiameter * 0.4;

        let currentDepth = 0;
        while (currentDepth < rabbetDepth) {
          currentDepth = Math.min(currentDepth + stepDown, rabbetDepth);

          // The rabbet is always a rectangular pocket along the edge
          let xStart: number, xEnd: number, yStart: number, yEnd: number;

          if (edge === "right") {
            xStart = startX;
            xEnd = startX + rabbetWidth;
            yStart = startY;
            yEnd = startY + rabbetLength;
          } else if (edge === "left") {
            xStart = startX - rabbetWidth;
            xEnd = startX;
            yStart = startY;
            yEnd = startY + rabbetLength;
          } else if (edge === "top") {
            xStart = startX;
            xEnd = startX + rabbetLength;
            yStart = startY;
            yEnd = startY + rabbetWidth;
          } else {
            // bottom
            xStart = startX;
            xEnd = startX + rabbetLength;
            yStart = startY - rabbetWidth;
            yEnd = startY;
          }

          // Raster the pocket area
          const cutXStart = xStart + toolRadius;
          const cutXEnd = xEnd - toolRadius;
          const cutYStart = yStart + toolRadius;
          const cutYEnd = yEnd - toolRadius;

          if (cutXEnd <= cutXStart || cutYEnd <= cutYStart) {
            return err("Rabbet dimensions too small for the tool diameter.");
          }

          let y = cutYStart;
          let leftToRight = true;
          gcode.push(`G0 X${cutXStart.toFixed(3)} Y${cutYStart.toFixed(3)}`);
          gcode.push(`G1 Z${(-currentDepth).toFixed(3)} F${Math.round(feedrate / 3)}`);

          while (y <= cutYEnd + 0.001) {
            if (leftToRight) {
              gcode.push(`G1 X${cutXEnd.toFixed(3)} Y${Math.min(y, cutYEnd).toFixed(3)} F${feedrate}`);
            } else {
              gcode.push(`G1 X${cutXStart.toFixed(3)} Y${Math.min(y, cutYEnd).toFixed(3)} F${feedrate}`);
            }
            y = Math.min(y + stepOver, cutYEnd + 0.001);
            if (y <= cutYEnd + 0.001) {
              gcode.push(`G1 Y${Math.min(y, cutYEnd).toFixed(3)} F${feedrate}`);
            }
            leftToRight = !leftToRight;
          }

          gcode.push(`G0 Z${SAFE_Z}`);
        }

        gcode.push(...gcodeFooter());
        const gcodeStr = gcode.join("\n");

        if (autoLoad) {
          const name = `rabbet_${edge}_${wood}_${Date.now()}.nc`;
          client.loadGcode(name, gcodeStr);
          return text(`Rabbet joint G-code generated and loaded (${rabbetLength}mm, ${edge} edge, ${wood}, ${gcode.length} lines).\nUse start_job to execute.\n\nPreview:\n${gcodeStr}`);
        }
        return text(`Rabbet joint G-code generated (${gcode.length} lines):\n\n${gcodeStr}`);
      } catch (e: any) {
        return err(e.message);
      }
    }
  );

  // ── generate_mortise ──────────────────────────────────

  server.tool(
    "generate_mortise",
    "Generate G-code for a mortise (rectangular pocket for mortise-and-tenon joinery). The strongest traditional wood joint, used for table legs, door frames, and structural connections.",
    {
      mortiseLength: z.number().positive().describe("Length of the mortise slot (mm)"),
      mortiseWidth: z.number().positive().describe("Width of the mortise — should match tenon thickness (mm)"),
      mortiseDepth: z.number().positive().describe("Depth of the mortise — typically 2/3 to 3/4 of receiving member thickness (mm)"),
      centerX: z.number().default(0).describe("Center X position (mm)"),
      centerY: z.number().default(0).describe("Center Y position (mm)"),
      toolDiameter: z.number().positive().describe("End mill diameter (mm) — must be <= mortise width"),
      wood: z.enum(["pine", "oak", "walnut", "maple", "cherry", "birch", "cedar", "plywood", "mdf", "bamboo"]).default("oak").describe("Wood type for automatic feed/speed selection"),
      feedrate: z.number().positive().optional().describe("Override cutting feed rate (mm/min)"),
      spindleSpeed: z.number().positive().optional().describe("Override spindle speed (RPM)"),
      autoLoad: z.boolean().default(true).describe("Automatically load into CNCjs (default true)"),
    },
    async (params) => {
      try {
        const { mortiseLength, mortiseWidth, mortiseDepth, centerX, centerY, toolDiameter, wood, autoLoad } = params;
        const preset = WOOD_PRESETS[wood];
        const feedrate = params.feedrate ?? preset.feedrate;
        const spindleSpeed = params.spindleSpeed ?? preset.spindleSpeed;
        const stepDown = preset.stepDown;
        const toolRadius = toolDiameter / 2;

        if (mortiseWidth < toolDiameter) {
          return err(`Mortise width (${mortiseWidth}mm) must be >= tool diameter (${toolDiameter}mm).`);
        }
        if (mortiseLength < toolDiameter) {
          return err(`Mortise length (${mortiseLength}mm) must be >= tool diameter (${toolDiameter}mm).`);
        }

        const gcode: string[] = [...gcodeHeader(spindleSpeed)];
        gcode.push(`; Mortise: ${mortiseLength}x${mortiseWidth}mm, ${mortiseDepth}mm deep`);
        gcode.push(`; Wood: ${wood} (${preset.description})`);

        const xStart = centerX - mortiseLength / 2 + toolRadius;
        const xEnd = centerX + mortiseLength / 2 - toolRadius;
        const yStart = centerY - mortiseWidth / 2 + toolRadius;
        const yEnd = centerY + mortiseWidth / 2 - toolRadius;
        const stepOver = toolDiameter * 0.4;

        let currentDepth = 0;
        while (currentDepth < mortiseDepth) {
          currentDepth = Math.min(currentDepth + stepDown, mortiseDepth);

          gcode.push(`G0 X${xStart.toFixed(3)} Y${yStart.toFixed(3)}`);
          gcode.push(`G1 Z${(-currentDepth).toFixed(3)} F${Math.round(feedrate / 3)} ; Plunge`);

          // Raster the mortise pocket
          let y = yStart;
          let leftToRight = true;
          while (y <= yEnd + 0.001) {
            if (leftToRight) {
              gcode.push(`G1 X${xEnd.toFixed(3)} Y${Math.min(y, yEnd).toFixed(3)} F${feedrate}`);
            } else {
              gcode.push(`G1 X${xStart.toFixed(3)} Y${Math.min(y, yEnd).toFixed(3)} F${feedrate}`);
            }
            y = Math.min(y + stepOver, yEnd + 0.001);
            if (y <= yEnd + 0.001) {
              gcode.push(`G1 Y${Math.min(y, yEnd).toFixed(3)} F${feedrate}`);
            }
            leftToRight = !leftToRight;
          }

          gcode.push(`G0 Z${SAFE_Z}`);
        }

        gcode.push(...gcodeFooter());
        const gcodeStr = gcode.join("\n");

        if (autoLoad) {
          const name = `mortise_${wood}_${Date.now()}.nc`;
          client.loadGcode(name, gcodeStr);
          return text(`Mortise G-code generated and loaded (${mortiseLength}x${mortiseWidth}mm, ${mortiseDepth}mm deep, ${wood}, ${gcode.length} lines).\nUse start_job to execute.\n\nPreview:\n${gcodeStr}`);
        }
        return text(`Mortise G-code generated (${gcode.length} lines):\n\n${gcodeStr}`);
      } catch (e: any) {
        return err(e.message);
      }
    }
  );

  // ── get_wood_settings ──────────────────────────────────

  server.tool(
    "get_wood_settings",
    "Get recommended CNC feed rates, spindle speeds, and step-down values for a specific wood type. Helps determine safe and effective cutting parameters.",
    {
      wood: z.enum(["pine", "oak", "walnut", "maple", "cherry", "birch", "cedar", "plywood", "mdf", "bamboo"]).optional().describe("Specific wood type to query. Omit to list all presets."),
      toolDiameter: z.number().positive().optional().describe("Tool diameter (mm) — adjusts recommendations for the specific bit size"),
    },
    async (params) => {
      try {
        if (params.wood) {
          const preset = WOOD_PRESETS[params.wood];
          const result: Record<string, unknown> = {
            wood: params.wood,
            ...preset,
            units: { feedrate: "mm/min", spindleSpeed: "RPM", stepDown: "mm" },
          };
          if (params.toolDiameter) {
            result.toolDiameter = params.toolDiameter;
            result.adjustedStepDown = Math.min(preset.stepDown, params.toolDiameter);
            result.chipLoad = (preset.feedrate / preset.spindleSpeed / 2).toFixed(4) + " mm/tooth (2-flute)";
          }
          return json(result);
        }
        // List all presets
        const allPresets = Object.entries(WOOD_PRESETS).map(([name, preset]) => ({
          wood: name,
          ...preset,
        }));
        return json({ presets: allPresets, units: { feedrate: "mm/min", spindleSpeed: "RPM", stepDown: "mm" } });
      } catch (e: any) {
        return err(e.message);
      }
    }
  );

  // ── generate_shelf_pin_holes ──────────────────────────────

  server.tool(
    "generate_shelf_pin_holes",
    "Generate G-code for shelf pin hole patterns. Drills two parallel columns of holes for adjustable shelf pins, standard in bookcases and cabinets.",
    {
      panelHeight: z.number().positive().describe("Height of the side panel (mm)"),
      holeSpacing: z.number().positive().default(32).describe("Vertical spacing between holes (mm, default 32mm — industry standard)"),
      rowSpacing: z.number().positive().describe("Horizontal distance between the two columns of holes (mm)"),
      holeDepth: z.number().positive().default(12).describe("Depth of each pin hole (mm, default 12)"),
      holeDiameter: z.number().positive().default(5).describe("Diameter of shelf pin holes (mm, default 5mm — standard)"),
      marginTop: z.number().positive().default(50).describe("Distance from top of panel to first hole (mm)"),
      marginBottom: z.number().positive().default(50).describe("Distance from bottom of panel to last hole (mm)"),
      startX: z.number().default(0).describe("Starting X position — left column (mm)"),
      startY: z.number().default(0).describe("Starting Y position — bottom of panel (mm)"),
      toolDiameter: z.number().positive().describe("Drill bit diameter (mm) — should match holeDiameter"),
      wood: z.enum(["pine", "oak", "walnut", "maple", "cherry", "birch", "cedar", "plywood", "mdf", "bamboo"]).default("plywood").describe("Wood type for automatic feed/speed selection"),
      feedrate: z.number().positive().optional().describe("Override drilling feed rate (mm/min)"),
      spindleSpeed: z.number().positive().optional().describe("Override spindle speed (RPM)"),
      autoLoad: z.boolean().default(true).describe("Automatically load into CNCjs (default true)"),
    },
    async (params) => {
      try {
        const { panelHeight, holeSpacing, rowSpacing, holeDepth, marginTop, marginBottom, startX, startY, toolDiameter, wood, autoLoad } = params;
        const preset = WOOD_PRESETS[wood];
        const feedrate = params.feedrate ?? Math.round(preset.feedrate * 0.5); // Slower for drilling
        const spindleSpeed = params.spindleSpeed ?? preset.spindleSpeed;

        const firstHoleY = startY + marginBottom;
        const lastHoleY = startY + panelHeight - marginTop;
        if (lastHoleY <= firstHoleY) return err("Panel too short for the specified margins.");

        const holeCount = Math.floor((lastHoleY - firstHoleY) / holeSpacing) + 1;
        const leftColumnX = startX;
        const rightColumnX = startX + rowSpacing;

        const gcode: string[] = [...gcodeHeader(spindleSpeed)];
        gcode.push(`; Shelf pin holes: ${holeCount} holes x 2 columns, ${holeSpacing}mm spacing`);
        gcode.push(`; Wood: ${wood}, hole depth: ${holeDepth}mm`);

        // Drill both columns
        for (const colX of [leftColumnX, rightColumnX]) {
          for (let i = 0; i < holeCount; i++) {
            const holeY = firstHoleY + i * holeSpacing;

            gcode.push(`G0 X${colX.toFixed(3)} Y${holeY.toFixed(3)}`);
            gcode.push(`G0 Z1 ; Approach`);

            // Peck drill for clean holes in wood
            const peckDepth = 3;
            let drilled = 0;
            while (drilled < holeDepth) {
              drilled = Math.min(drilled + peckDepth, holeDepth);
              gcode.push(`G1 Z${(-drilled).toFixed(3)} F${feedrate}`);
              gcode.push(`G0 Z1 ; Retract for chip clearing`);
            }

            gcode.push(`G0 Z${SAFE_Z}`);
          }
        }

        gcode.push(...gcodeFooter());
        const gcodeStr = gcode.join("\n");
        const totalHoles = holeCount * 2;

        if (autoLoad) {
          const name = `shelf_pins_${wood}_${Date.now()}.nc`;
          client.loadGcode(name, gcodeStr);
          return text(`Shelf pin holes G-code generated and loaded (${totalHoles} holes in 2 columns, ${wood}, ${gcode.length} lines).\nUse start_job to execute.\n\nPreview:\n${gcodeStr}`);
        }
        return text(`Shelf pin holes G-code generated (${totalHoles} holes, ${gcode.length} lines):\n\n${gcodeStr}`);
      } catch (e: any) {
        return err(e.message);
      }
    }
  );

  // ── calculate_material ──────────────────────────────────

  server.tool(
    "calculate_material",
    "Calculate wood material requirements for a carpentry project. Computes board feet, cut lists, and waste estimates to help plan material purchases.",
    {
      parts: z.array(z.object({
        name: z.string().describe("Part name (e.g., 'Side panel', 'Shelf')"),
        length: z.number().positive().describe("Part length (mm)"),
        width: z.number().positive().describe("Part width (mm)"),
        thickness: z.number().positive().describe("Part thickness (mm)"),
        quantity: z.number().int().positive().default(1).describe("Number of this part needed"),
      })).describe("List of parts with dimensions"),
      stockLength: z.number().positive().default(2440).describe("Available stock length (mm, default 2440mm / 8ft)"),
      stockWidth: z.number().positive().default(1220).describe("Available stock width (mm, default 1220mm / 4ft)"),
      kerfWidth: z.number().positive().default(3.2).describe("Saw blade kerf / CNC tool width (mm, default 3.2)"),
      wasteMargin: z.number().min(0).max(50).default(10).describe("Extra waste margin percentage (default 10%)"),
    },
    async ({ parts, stockLength, stockWidth, kerfWidth, wasteMargin }) => {
      try {
        let totalArea = 0;
        const cutList: { name: string; length: number; width: number; thickness: number; quantity: number; area: number }[] = [];

        for (const part of parts) {
          const area = (part.length + kerfWidth) * (part.width + kerfWidth) * part.quantity;
          totalArea += area;
          cutList.push({
            name: part.name,
            length: part.length,
            width: part.width,
            thickness: part.thickness,
            quantity: part.quantity,
            area: part.length * part.width * part.quantity,
          });
        }

        const stockArea = stockLength * stockWidth;
        const sheetsNeeded = Math.ceil(totalArea * (1 + wasteMargin / 100) / stockArea);
        const totalPartArea = cutList.reduce((sum, p) => sum + p.area, 0);

        // Board feet calculation (for solid lumber)
        const boardFeet = cutList.reduce((sum, p) => {
          return sum + (p.length / 25.4) * (p.width / 25.4) * (p.thickness / 25.4) / 144 * p.quantity;
        }, 0);

        const result = {
          cutList,
          summary: {
            totalParts: cutList.reduce((sum, p) => sum + p.quantity, 0),
            totalPartArea: `${(totalPartArea / 1000000).toFixed(3)} m²`,
            boardFeet: `${boardFeet.toFixed(1)} BF`,
            stockSheetSize: `${stockLength}x${stockWidth}mm`,
            sheetsNeeded,
            estimatedWaste: `${wasteMargin}%`,
            kerfWidth: `${kerfWidth}mm`,
          },
        };

        return json(result);
      } catch (e: any) {
        return err(e.message);
      }
    }
  );

  // ── generate_cut_list ──────────────────────────────────

  server.tool(
    "generate_cut_list",
    "Generate a detailed, formatted cut list for a woodworking project. Groups parts by thickness/material, includes grain direction and edge banding notes, and outputs a printable text or CSV file for the shop.",
    {
      projectName: z.string().describe("Name of the project (e.g., 'Kitchen Wall Cabinet')"),
      parts: z.array(z.object({
        name: z.string().describe("Part name (e.g., 'Side panel')"),
        length: z.number().positive().describe("Part length — along the grain (mm)"),
        width: z.number().positive().describe("Part width — across the grain (mm)"),
        thickness: z.number().positive().describe("Part thickness (mm)"),
        quantity: z.number().int().positive().default(1).describe("Number needed"),
        material: z.string().default("plywood").describe("Material (e.g., 'plywood', 'oak', 'pine', 'mdf')"),
        grainDirection: z.enum(["length", "width", "none"]).default("length").describe("Primary grain direction: 'length' (along L), 'width' (along W), or 'none' (MDF/plywood)"),
        edgeBanding: z.array(z.enum(["length1", "length2", "width1", "width2"])).default([]).describe("Which edges need banding: length1, length2 (long edges), width1, width2 (short edges)"),
        notes: z.string().optional().describe("Additional notes (e.g., 'miter left end 45°', 'drill shelf pin holes')"),
      })).describe("List of parts"),
      outputPath: z.string().optional().describe("File path to save the cut list (supports .txt or .csv)"),
      format: z.enum(["text", "csv"]).default("text").describe("Output format: 'text' for printable shop list, 'csv' for spreadsheet import"),
    },
    async (params: any) => {
      try {
        const { projectName, parts, outputPath, format } = params;

        // Group parts by material and thickness
        const groups = new Map<string, typeof parts>();
        for (const part of parts) {
          const key = `${part.material} ${part.thickness}mm`;
          if (!groups.has(key)) groups.set(key, []);
          groups.get(key)!.push(part);
        }

        let output: string;

        if (format === "csv") {
          const lines: string[] = [
            "Group,Part Name,Qty,Length (mm),Width (mm),Thickness (mm),Material,Grain,Edge Banding,Notes"
          ];
          for (const [group, groupParts] of groups) {
            for (const p of groupParts) {
              const eb = p.edgeBanding.length > 0 ? p.edgeBanding.join("+") : "-";
              const notes = p.notes ? `"${p.notes}"` : "";
              lines.push(`"${group}","${p.name}",${p.quantity},${p.length},${p.width},${p.thickness},"${p.material}","${p.grainDirection}","${eb}",${notes}`);
            }
          }
          output = lines.join("\n");
        } else {
          const lines: string[] = [];
          lines.push(`CUT LIST: ${projectName}`);
          lines.push(`${"=".repeat(70)}`);
          lines.push(`Generated: ${new Date().toISOString().split("T")[0]}`);
          lines.push("");

          let totalParts = 0;
          let partNumber = 1;

          for (const [group, groupParts] of groups) {
            lines.push(`── ${group.toUpperCase()} ${"─".repeat(Math.max(0, 55 - group.length))}`);
            lines.push("");
            lines.push(`  #   Qty  Part Name                  Length    Width     Grain   Edge Band`);
            lines.push(`  ${"─".repeat(66)}`);

            for (const p of groupParts) {
              const eb = p.edgeBanding.length > 0 ? p.edgeBanding.join("+") : "-";
              const grain = p.grainDirection === "none" ? "-" : p.grainDirection === "length" ? "L" : "W";
              const name = p.name.padEnd(26).slice(0, 26);
              lines.push(`  ${String(partNumber).padStart(2)}   ${String(p.quantity).padStart(2)}x  ${name} ${String(p.length).padStart(7)}  ${String(p.width).padStart(7)}     ${grain.padEnd(6)}  ${eb}`);
              if (p.notes) {
                lines.push(`                   → ${p.notes}`);
              }
              totalParts += p.quantity;
              partNumber++;
            }
            lines.push("");
          }

          lines.push(`${"=".repeat(70)}`);
          lines.push(`TOTAL: ${partNumber - 1} unique parts, ${totalParts} pieces`);
          lines.push("");

          // Edge banding summary
          const bandedParts = parts.filter((p: any) => p.edgeBanding.length > 0);
          if (bandedParts.length > 0) {
            lines.push("EDGE BANDING REQUIRED:");
            let totalBandingLength = 0;
            for (const p of bandedParts) {
              for (const edge of p.edgeBanding) {
                const edgeLen = edge.startsWith("length") ? p.length : p.width;
                totalBandingLength += edgeLen * p.quantity;
              }
            }
            lines.push(`  Total banding length: ${(totalBandingLength / 1000).toFixed(1)}m (${Math.ceil(totalBandingLength / 1000 * 1.1)}m with 10% waste)`);
            lines.push("");
          }

          output = lines.join("\n");
        }

        if (outputPath) {
          writeFileSync(outputPath, output, "utf-8");
          return text(`Cut list saved to ${outputPath}\n\n${output}`);
        }
        return text(output);
      } catch (e: any) {
        return err(e.message);
      }
    }
  );

  // ── generate_project_schematic ──────────────────────────────

  server.tool(
    "generate_project_schematic",
    "Generate an SVG schematic drawing for a woodworking project. Creates dimensioned part diagrams showing each piece with measurements, grain direction arrows, and joinery locations. Useful as a shop drawing or visual reference.",
    {
      projectName: z.string().describe("Project name for the title block"),
      parts: z.array(z.object({
        name: z.string().describe("Part name"),
        length: z.number().positive().describe("Part length (mm)"),
        width: z.number().positive().describe("Part width (mm)"),
        thickness: z.number().positive().describe("Part thickness (mm)"),
        features: z.array(z.object({
          type: z.enum(["dado", "rabbet", "mortise", "hole", "chamfer"]).describe("Feature type"),
          x: z.number().describe("Feature X position relative to part origin (mm)"),
          y: z.number().describe("Feature Y position relative to part origin (mm)"),
          width: z.number().positive().optional().describe("Feature width (mm)"),
          height: z.number().positive().optional().describe("Feature height/length (mm)"),
          diameter: z.number().positive().optional().describe("Hole diameter (mm)"),
          depth: z.number().positive().optional().describe("Feature depth (mm)"),
          label: z.string().optional().describe("Label text for the feature"),
        })).default([]).describe("Joinery features to show on the part"),
      })).describe("Parts to draw"),
      columns: z.number().int().min(1).max(4).default(2).describe("Number of columns in the layout (default 2)"),
      scale: z.number().positive().default(0.5).describe("Drawing scale relative to real size (default 0.5 = half size)"),
      outputPath: z.string().describe("File path to save the SVG schematic"),
    },
    async (params: any) => {
      try {
        const { projectName, parts, columns, scale, outputPath } = params;

        const padding = 30;
        const partSpacing = 40;
        const titleHeight = 50;
        const dimOffset = 15; // dimension line offset from part edge

        // Calculate layout
        const scaledParts = parts.map((p: any) => ({
          ...p,
          sw: p.length * scale,
          sh: p.width * scale,
        }));

        // Arrange in grid
        const rows = Math.ceil(scaledParts.length / columns);
        const colWidths: number[] = [];
        const rowHeights: number[] = [];

        for (let c = 0; c < columns; c++) {
          let maxW = 0;
          for (let r = 0; r < rows; r++) {
            const idx = r * columns + c;
            if (idx < scaledParts.length) maxW = Math.max(maxW, scaledParts[idx].sw);
          }
          colWidths.push(maxW + dimOffset * 2);
        }
        for (let r = 0; r < rows; r++) {
          let maxH = 0;
          for (let c = 0; c < columns; c++) {
            const idx = r * columns + c;
            if (idx < scaledParts.length) maxH = Math.max(maxH, scaledParts[idx].sh);
          }
          rowHeights.push(maxH + dimOffset * 2 + 30); // 30 for label text
        }

        const totalW = colWidths.reduce((a, b) => a + b, 0) + partSpacing * (columns - 1) + padding * 2;
        const totalH = rowHeights.reduce((a, b) => a + b, 0) + partSpacing * (rows - 1) + padding * 2 + titleHeight;

        let svg = `<?xml version="1.0" encoding="UTF-8"?>\n`;
        svg += `<svg xmlns="http://www.w3.org/2000/svg" width="${totalW}mm" height="${totalH}mm" viewBox="0 0 ${totalW} ${totalH}">\n`;
        svg += `  <style>\n`;
        svg += `    text { font-family: Arial, sans-serif; }\n`;
        svg += `    .title { font-size: 14px; font-weight: bold; }\n`;
        svg += `    .part-label { font-size: 9px; font-weight: bold; }\n`;
        svg += `    .dim-text { font-size: 7px; }\n`;
        svg += `    .feature-label { font-size: 6px; fill: #666; }\n`;
        svg += `    .part-outline { fill: #fef3c7; stroke: #92400e; stroke-width: 0.5; }\n`;
        svg += `    .feature { fill: #d1d5db; stroke: #6b7280; stroke-width: 0.3; }\n`;
        svg += `    .dim-line { stroke: #374151; stroke-width: 0.3; marker-end: url(#arrow); marker-start: url(#arrow-start); }\n`;
        svg += `    .grain-arrow { stroke: #92400e; stroke-width: 0.3; fill: none; stroke-dasharray: 2,2; }\n`;
        svg += `  </style>\n`;
        svg += `  <defs>\n`;
        svg += `    <marker id="arrow" markerWidth="6" markerHeight="4" refX="6" refY="2" orient="auto"><path d="M0,0 L6,2 L0,4" fill="#374151" /></marker>\n`;
        svg += `    <marker id="arrow-start" markerWidth="6" markerHeight="4" refX="0" refY="2" orient="auto"><path d="M6,0 L0,2 L6,4" fill="#374151" /></marker>\n`;
        svg += `  </defs>\n`;

        // Title
        svg += `  <text x="${totalW / 2}" y="${padding + 15}" text-anchor="middle" class="title">${projectName} — Parts Schematic</text>\n`;
        svg += `  <line x1="${padding}" y1="${padding + 25}" x2="${totalW - padding}" y2="${padding + 25}" stroke="#374151" stroke-width="0.5" />\n`;

        // Draw each part
        let partIdx = 0;
        for (let r = 0; r < rows; r++) {
          for (let c = 0; c < columns; c++) {
            if (partIdx >= scaledParts.length) break;
            const part = scaledParts[partIdx];

            // Calculate position
            let px = padding + dimOffset;
            for (let cc = 0; cc < c; cc++) px += colWidths[cc] + partSpacing;
            let py = padding + titleHeight + dimOffset;
            for (let rr = 0; rr < r; rr++) py += rowHeights[rr] + partSpacing;

            // Part rectangle
            svg += `  <rect x="${px}" y="${py}" width="${part.sw}" height="${part.sh}" class="part-outline" />\n`;

            // Part label
            svg += `  <text x="${px + part.sw / 2}" y="${py - dimOffset - 3}" text-anchor="middle" class="part-label">${part.name} (${part.thickness}mm thick)</text>\n`;

            // Grain direction arrow (dashed line with arrow along length)
            if (part.sh > 10 && part.sw > 20) {
              const arrowY = py + part.sh / 2;
              svg += `  <line x1="${px + 5}" y1="${arrowY}" x2="${px + part.sw - 5}" y2="${arrowY}" class="grain-arrow" />\n`;
              // Arrowhead
              svg += `  <polygon points="${px + part.sw - 8},${arrowY - 2} ${px + part.sw - 5},${arrowY} ${px + part.sw - 8},${arrowY + 2}" fill="#92400e" opacity="0.6" />\n`;
            }

            // Length dimension (top)
            const dimY = py - 5;
            svg += `  <line x1="${px}" y1="${dimY}" x2="${px + part.sw}" y2="${dimY}" class="dim-line" />\n`;
            svg += `  <text x="${px + part.sw / 2}" y="${dimY - 2}" text-anchor="middle" class="dim-text">${part.length}mm</text>\n`;

            // Width dimension (right)
            const dimX = px + part.sw + 5;
            svg += `  <line x1="${dimX}" y1="${py}" x2="${dimX}" y2="${py + part.sh}" class="dim-line" />\n`;
            svg += `  <text x="${dimX + 3}" y="${py + part.sh / 2 + 3}" class="dim-text">${part.width}mm</text>\n`;

            // Draw features (joinery, holes, etc.)
            for (const feat of part.features) {
              const fx = px + feat.x * scale;
              const fy = py + feat.y * scale;

              if (feat.type === "hole" && feat.diameter) {
                const sr = feat.diameter * scale / 2;
                svg += `  <circle cx="${fx}" cy="${fy}" r="${sr}" class="feature" />\n`;
                if (feat.label) {
                  svg += `  <text x="${fx}" y="${fy + sr + 8}" text-anchor="middle" class="feature-label">${feat.label}</text>\n`;
                }
              } else {
                // Rectangular features (dado, rabbet, mortise, chamfer)
                const fw = (feat.width ?? 10) * scale;
                const fh = (feat.height ?? 10) * scale;
                svg += `  <rect x="${fx - fw / 2}" y="${fy - fh / 2}" width="${fw}" height="${fh}" class="feature" />\n`;
                if (feat.label) {
                  svg += `  <text x="${fx}" y="${fy + fh / 2 + 8}" text-anchor="middle" class="feature-label">${feat.label}</text>\n`;
                }
              }
            }

            partIdx++;
          }
        }

        svg += `</svg>\n`;

        writeFileSync(outputPath, svg, "utf-8");
        return text(`Schematic SVG saved to ${outputPath} (${parts.length} parts, scale ${scale}:1, ${totalW.toFixed(0)}x${totalH.toFixed(0)}mm)\n\nOpen in a browser or SVG viewer to see the dimensioned parts drawing.`);
      } catch (e: any) {
        return err(e.message);
      }
    }
  );

  // ── generate_materials_list ──────────────────────────────

  server.tool(
    "generate_materials_list",
    "Generate a complete bill of materials (BOM) for a woodworking project. Includes lumber/sheet goods, hardware (screws, hinges, pulls), edge banding, adhesives, and finishing supplies with estimated costs.",
    {
      projectName: z.string().describe("Project name"),
      lumber: z.array(z.object({
        material: z.string().describe("Material name (e.g., '3/4 Baltic Birch Plywood', '4/4 Red Oak')"),
        thickness: z.number().positive().describe("Thickness in mm"),
        quantity: z.number().positive().describe("Amount needed — board feet for solid, sheets for plywood"),
        unit: z.enum(["board_feet", "sheets", "linear_feet", "pieces"]).describe("Quantity unit"),
        unitCost: z.number().min(0).optional().describe("Cost per unit in local currency"),
      })).default([]).describe("Lumber and sheet goods"),
      hardware: z.array(z.object({
        item: z.string().describe("Hardware item name (e.g., '35mm Euro hinges', '#8 x 1-1/4 screws')"),
        quantity: z.number().positive().describe("Number needed"),
        unitCost: z.number().min(0).optional().describe("Cost per item"),
        supplier: z.string().optional().describe("Where to buy"),
      })).default([]).describe("Hardware items: screws, hinges, pulls, shelf pins, slides, etc."),
      edgeBanding: z.array(z.object({
        material: z.string().describe("Edge banding material (e.g., 'White oak iron-on')"),
        lengthMeters: z.number().positive().describe("Total length needed in meters"),
        widthMm: z.number().positive().default(22).describe("Banding width in mm"),
        unitCost: z.number().min(0).optional().describe("Cost per meter"),
      })).default([]).describe("Edge banding materials"),
      finishing: z.array(z.object({
        product: z.string().describe("Finish product name (e.g., 'Arm-R-Seal satin', 'Minwax Provincial stain')"),
        quantity: z.number().positive().describe("Amount needed"),
        unit: z.enum(["quarts", "pints", "gallons", "cans", "sheets"]).describe("Quantity unit"),
        unitCost: z.number().min(0).optional().describe("Cost per unit"),
      })).default([]).describe("Finishing supplies: stains, sealers, topcoats, sandpaper"),
      adhesives: z.array(z.object({
        product: z.string().describe("Adhesive name (e.g., 'Titebond III', 'CA glue')"),
        quantity: z.number().positive().default(1).describe("Number of bottles/tubes"),
        unitCost: z.number().min(0).optional().describe("Cost per unit"),
      })).default([]).describe("Glues and adhesives"),
      outputPath: z.string().optional().describe("File path to save the materials list (.txt or .csv)"),
      format: z.enum(["text", "csv"]).default("text").describe("Output format"),
    },
    async (params: any) => {
      try {
        const { projectName, lumber, hardware, edgeBanding, finishing, adhesives, outputPath, format } = params;

        const calcSubtotal = (items: { unitCost?: number; quantity: number }[]) =>
          items.reduce((sum, item) => sum + (item.unitCost ?? 0) * item.quantity, 0);

        const lumberCost = calcSubtotal(lumber);
        const hardwareCost = calcSubtotal(hardware);
        const bandingCost = edgeBanding.reduce((sum: number, eb: any) => sum + (eb.unitCost ?? 0) * eb.lengthMeters, 0);
        const finishCost = calcSubtotal(finishing);
        const adhesiveCost = calcSubtotal(adhesives);
        const totalCost = lumberCost + hardwareCost + bandingCost + finishCost + adhesiveCost;

        let output: string;

        if (format === "csv") {
          const lines: string[] = ["Category,Item,Quantity,Unit,Unit Cost,Subtotal"];
          for (const l of lumber) lines.push(`Lumber,"${l.material}",${l.quantity},${l.unit},${l.unitCost ?? ""},${((l.unitCost ?? 0) * l.quantity).toFixed(2)}`);
          for (const h of hardware) lines.push(`Hardware,"${h.item}",${h.quantity},pcs,${h.unitCost ?? ""},${((h.unitCost ?? 0) * h.quantity).toFixed(2)}`);
          for (const eb of edgeBanding) lines.push(`Edge Banding,"${eb.material}",${eb.lengthMeters},meters,${eb.unitCost ?? ""},${((eb.unitCost ?? 0) * eb.lengthMeters).toFixed(2)}`);
          for (const f of finishing) lines.push(`Finishing,"${f.product}",${f.quantity},${f.unit},${f.unitCost ?? ""},${((f.unitCost ?? 0) * f.quantity).toFixed(2)}`);
          for (const a of adhesives) lines.push(`Adhesives,"${a.product}",${a.quantity},bottles,${a.unitCost ?? ""},${((a.unitCost ?? 0) * a.quantity).toFixed(2)}`);
          lines.push(`,,,,TOTAL,${totalCost.toFixed(2)}`);
          output = lines.join("\n");
        } else {
          const lines: string[] = [];
          lines.push(`MATERIALS LIST: ${projectName}`);
          lines.push(`${"=".repeat(70)}`);
          lines.push(`Generated: ${new Date().toISOString().split("T")[0]}`);
          lines.push("");

          if (lumber.length > 0) {
            lines.push("LUMBER & SHEET GOODS");
            lines.push(`${"─".repeat(70)}`);
            for (const l of lumber) {
              const cost = l.unitCost ? `$${(l.unitCost * l.quantity).toFixed(2)}` : "";
              lines.push(`  ${l.material.padEnd(40)} ${String(l.quantity).padStart(5)} ${l.unit.padEnd(12)} ${cost}`);
            }
            if (lumberCost > 0) lines.push(`${"".padStart(58)}Subtotal: $${lumberCost.toFixed(2)}`);
            lines.push("");
          }

          if (hardware.length > 0) {
            lines.push("HARDWARE");
            lines.push(`${"─".repeat(70)}`);
            for (const h of hardware) {
              const cost = h.unitCost ? `$${(h.unitCost * h.quantity).toFixed(2)}` : "";
              const supplier = h.supplier ? ` [${h.supplier}]` : "";
              lines.push(`  ${h.item.padEnd(40)} ${String(h.quantity).padStart(5)} pcs${" ".repeat(8)} ${cost}${supplier}`);
            }
            if (hardwareCost > 0) lines.push(`${"".padStart(58)}Subtotal: $${hardwareCost.toFixed(2)}`);
            lines.push("");
          }

          if (edgeBanding.length > 0) {
            lines.push("EDGE BANDING");
            lines.push(`${"─".repeat(70)}`);
            for (const eb of edgeBanding) {
              const cost = eb.unitCost ? `$${(eb.unitCost * eb.lengthMeters).toFixed(2)}` : "";
              lines.push(`  ${eb.material.padEnd(40)} ${String(eb.lengthMeters).padStart(5)}m (${eb.widthMm}mm)${" ".repeat(3)} ${cost}`);
            }
            if (bandingCost > 0) lines.push(`${"".padStart(58)}Subtotal: $${bandingCost.toFixed(2)}`);
            lines.push("");
          }

          if (finishing.length > 0) {
            lines.push("FINISHING SUPPLIES");
            lines.push(`${"─".repeat(70)}`);
            for (const f of finishing) {
              const cost = f.unitCost ? `$${(f.unitCost * f.quantity).toFixed(2)}` : "";
              lines.push(`  ${f.product.padEnd(40)} ${String(f.quantity).padStart(5)} ${f.unit.padEnd(12)} ${cost}`);
            }
            if (finishCost > 0) lines.push(`${"".padStart(58)}Subtotal: $${finishCost.toFixed(2)}`);
            lines.push("");
          }

          if (adhesives.length > 0) {
            lines.push("ADHESIVES");
            lines.push(`${"─".repeat(70)}`);
            for (const a of adhesives) {
              const cost = a.unitCost ? `$${(a.unitCost * a.quantity).toFixed(2)}` : "";
              lines.push(`  ${a.product.padEnd(40)} ${String(a.quantity).padStart(5)} bottles${" ".repeat(5)} ${cost}`);
            }
            if (adhesiveCost > 0) lines.push(`${"".padStart(58)}Subtotal: $${adhesiveCost.toFixed(2)}`);
            lines.push("");
          }

          lines.push(`${"=".repeat(70)}`);
          if (totalCost > 0) {
            lines.push(`ESTIMATED TOTAL: $${totalCost.toFixed(2)}`);
          }
          lines.push("");

          output = lines.join("\n");
        }

        if (outputPath) {
          writeFileSync(outputPath, output, "utf-8");
          return text(`Materials list saved to ${outputPath}\n\n${output}`);
        }
        return text(output);
      } catch (e: any) {
        return err(e.message);
      }
    }
  );
}
