// Design tools: G-code generation, SVG/DXF file generation

import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { z } from "zod";
import { client } from "../cncjs-client.js";
import { writeFileSync } from "fs";

function text(s: string) {
  return { content: [{ type: "text" as const, text: s }] };
}

function json(obj: unknown) {
  return text(JSON.stringify(obj, null, 2));
}

function err(s: string) {
  return { content: [{ type: "text" as const, text: s }], isError: true };
}

// ── G-code helpers ──────────────────────────────────────────

const SAFE_Z = 5; // mm above work surface for rapids

function gcodeHeader(spindleSpeed: number): string[] {
  return [
    "; Generated by CNC-design-control-MCP",
    "G90 G21 ; Absolute positioning, millimeters",
    "G17 ; XY plane",
    `G0 Z${SAFE_Z} ; Retract to safe height`,
    `M3 S${spindleSpeed} ; Spindle on CW`,
    "G4 P2 ; Dwell 2s for spindle to reach speed",
  ];
}

function gcodeFooter(): string[] {
  return [
    `G0 Z${SAFE_Z} ; Retract to safe height`,
    "M5 ; Spindle off",
    "G0 X0 Y0 ; Return to origin",
    "M2 ; Program end",
  ];
}

function circlePoints(cx: number, cy: number, radius: number, segments: number = 72): [number, number][] {
  const pts: [number, number][] = [];
  for (let i = 0; i <= segments; i++) {
    const angle = (2 * Math.PI * i) / segments;
    pts.push([cx + radius * Math.cos(angle), cy + radius * Math.sin(angle)]);
  }
  return pts;
}

function rectPoints(cx: number, cy: number, width: number, height: number): [number, number][] {
  const hw = width / 2, hh = height / 2;
  return [
    [cx - hw, cy - hh],
    [cx + hw, cy - hh],
    [cx + hw, cy + hh],
    [cx - hw, cy + hh],
    [cx - hw, cy - hh], // close
  ];
}

export function registerDesignTools(server: McpServer): void {
  // ── generate_gcode_profile ──────────────────────────────────

  server.tool(
    "generate_gcode_profile",
    "Generate G-code to cut a 2D profile (circle, rectangle, or custom path). Multi-pass step-down with safe retracts.",
    {
      shape: z.enum(["circle", "rectangle", "custom"]).describe("Shape type"),
      centerX: z.number().default(0).describe("Center X position (mm, default 0)"),
      centerY: z.number().default(0).describe("Center Y position (mm, default 0)"),
      radius: z.number().positive().optional().describe("Radius for circle (mm)"),
      width: z.number().positive().optional().describe("Width for rectangle (mm)"),
      height: z.number().positive().optional().describe("Height for rectangle (mm)"),
      points: z.array(z.tuple([z.number(), z.number()])).optional().describe("Custom path points as [x,y] pairs"),
      depth: z.number().positive().describe("Total cut depth (mm)"),
      stepDown: z.number().positive().describe("Depth per pass (mm)"),
      feedrate: z.number().positive().describe("Cutting feed rate (mm/min)"),
      spindleSpeed: z.number().positive().describe("Spindle speed (RPM)"),
      toolDiameter: z.number().positive().describe("Tool diameter for offset compensation (mm)"),
      compensation: z.enum(["inside", "outside", "none"]).default("none").describe("Tool compensation: inside/outside the path, or none (center on line)"),
      autoLoad: z.boolean().default(true).describe("Automatically load the generated G-code into CNCjs (default true)"),
    },
    async (params) => {
      try {
        const { shape, centerX, centerY, depth, stepDown, feedrate, spindleSpeed, toolDiameter, compensation, autoLoad } = params;

        // Get path points
        let pts: [number, number][];
        if (shape === "circle") {
          if (!params.radius) return err("Radius is required for circle profile.");
          let r = params.radius;
          if (compensation === "outside") r += toolDiameter / 2;
          else if (compensation === "inside") r -= toolDiameter / 2;
          if (r <= 0) return err("Effective radius is zero or negative after tool compensation.");
          pts = circlePoints(centerX, centerY, r);
        } else if (shape === "rectangle") {
          if (!params.width || !params.height) return err("Width and height are required for rectangle profile.");
          let w = params.width, h = params.height;
          if (compensation === "outside") { w += toolDiameter; h += toolDiameter; }
          else if (compensation === "inside") { w -= toolDiameter; h -= toolDiameter; }
          if (w <= 0 || h <= 0) return err("Effective dimensions are zero or negative after tool compensation.");
          pts = rectPoints(centerX, centerY, w, h);
        } else {
          if (!params.points || params.points.length < 2) return err("At least 2 points are required for custom profile.");
          pts = params.points as [number, number][];
        }

        const gcode: string[] = [...gcodeHeader(spindleSpeed)];

        // Multi-pass step-down
        let currentDepth = 0;
        while (currentDepth < depth) {
          currentDepth = Math.min(currentDepth + stepDown, depth);

          // Rapid to start position
          gcode.push(`G0 X${pts[0][0].toFixed(3)} Y${pts[0][1].toFixed(3)}`);
          // Plunge
          gcode.push(`G1 Z${(-currentDepth).toFixed(3)} F${Math.round(feedrate / 3)} ; Plunge to depth`);
          // Cut profile
          for (let i = 1; i < pts.length; i++) {
            gcode.push(`G1 X${pts[i][0].toFixed(3)} Y${pts[i][1].toFixed(3)} F${feedrate}`);
          }
          // Retract
          gcode.push(`G0 Z${SAFE_Z}`);
        }

        gcode.push(...gcodeFooter());
        const gcodeStr = gcode.join("\n");

        if (autoLoad) {
          const name = `profile_${shape}_${Date.now()}.nc`;
          client.loadGcode(name, gcodeStr);
          return text(`Profile G-code generated and loaded (${gcode.length} lines, ${shape}).\nUse start_job to execute.\n\nPreview:\n${gcodeStr}`);
        }
        return text(`Profile G-code generated (${gcode.length} lines):\n\n${gcodeStr}`);
      } catch (e: any) {
        return err(e.message);
      }
    }
  );

  // ── generate_gcode_pocket ──────────────────────────────────

  server.tool(
    "generate_gcode_pocket",
    "Generate G-code to clear a rectangular or circular pocket with raster pattern. Multi-pass step-down.",
    {
      shape: z.enum(["rectangle", "circle"]).describe("Pocket shape"),
      centerX: z.number().default(0).describe("Center X position (mm)"),
      centerY: z.number().default(0).describe("Center Y position (mm)"),
      width: z.number().positive().optional().describe("Width for rectangular pocket (mm)"),
      height: z.number().positive().optional().describe("Height for rectangular pocket (mm)"),
      radius: z.number().positive().optional().describe("Radius for circular pocket (mm)"),
      depth: z.number().positive().describe("Total pocket depth (mm)"),
      stepDown: z.number().positive().describe("Depth per pass (mm)"),
      stepOver: z.number().min(10).max(90).default(40).describe("Step-over as % of tool diameter (default 40%)"),
      feedrate: z.number().positive().describe("Cutting feed rate (mm/min)"),
      spindleSpeed: z.number().positive().describe("Spindle speed (RPM)"),
      toolDiameter: z.number().positive().describe("Tool diameter (mm)"),
      autoLoad: z.boolean().default(true).describe("Automatically load into CNCjs (default true)"),
    },
    async (params) => {
      try {
        const { shape, centerX, centerY, depth, stepDown, stepOver, feedrate, spindleSpeed, toolDiameter, autoLoad } = params;
        const stepOverDist = toolDiameter * (stepOver / 100);

        const gcode: string[] = [...gcodeHeader(spindleSpeed)];

        let currentDepth = 0;
        while (currentDepth < depth) {
          currentDepth = Math.min(currentDepth + stepDown, depth);

          if (shape === "rectangle") {
            if (!params.width || !params.height) return err("Width and height required for rectangular pocket.");
            // Inset by tool radius
            const w = params.width - toolDiameter;
            const h = params.height - toolDiameter;
            if (w <= 0 || h <= 0) return err("Pocket too small for tool diameter.");

            const xStart = centerX - w / 2;
            const xEnd = centerX + w / 2;
            const yStart = centerY - h / 2;
            const yEnd = centerY + h / 2;

            // Raster pattern
            gcode.push(`G0 X${xStart.toFixed(3)} Y${yStart.toFixed(3)}`);
            gcode.push(`G1 Z${(-currentDepth).toFixed(3)} F${Math.round(feedrate / 3)}`);

            let y = yStart;
            let leftToRight = true;
            while (y <= yEnd) {
              if (leftToRight) {
                gcode.push(`G1 X${xEnd.toFixed(3)} Y${y.toFixed(3)} F${feedrate}`);
              } else {
                gcode.push(`G1 X${xStart.toFixed(3)} Y${y.toFixed(3)} F${feedrate}`);
              }
              y = Math.min(y + stepOverDist, yEnd + 0.001);
              if (y <= yEnd + 0.001) {
                gcode.push(`G1 Y${Math.min(y, yEnd).toFixed(3)} F${feedrate}`);
              }
              leftToRight = !leftToRight;
            }
          } else {
            // Circular pocket — spiral from center out
            if (!params.radius) return err("Radius required for circular pocket.");
            const maxR = params.radius - toolDiameter / 2;
            if (maxR <= 0) return err("Pocket too small for tool diameter.");

            gcode.push(`G0 X${centerX.toFixed(3)} Y${centerY.toFixed(3)}`);
            gcode.push(`G1 Z${(-currentDepth).toFixed(3)} F${Math.round(feedrate / 3)}`);

            // Spiral outward
            let r = stepOverDist;
            while (r <= maxR) {
              const segments = Math.max(36, Math.round(2 * Math.PI * r / 2));
              for (let i = 0; i <= segments; i++) {
                const angle = (2 * Math.PI * i) / segments;
                const expandR = r + (stepOverDist * i) / segments;
                const clampedR = Math.min(expandR, maxR);
                const px = centerX + clampedR * Math.cos(angle);
                const py = centerY + clampedR * Math.sin(angle);
                gcode.push(`G1 X${px.toFixed(3)} Y${py.toFixed(3)} F${feedrate}`);
              }
              r += stepOverDist;
            }

            // Final perimeter pass
            const perimPts = circlePoints(centerX, centerY, maxR, 72);
            for (const [px, py] of perimPts) {
              gcode.push(`G1 X${px.toFixed(3)} Y${py.toFixed(3)} F${feedrate}`);
            }
          }

          gcode.push(`G0 Z${SAFE_Z}`);
        }

        gcode.push(...gcodeFooter());
        const gcodeStr = gcode.join("\n");

        if (autoLoad) {
          const name = `pocket_${shape}_${Date.now()}.nc`;
          client.loadGcode(name, gcodeStr);
          return text(`Pocket G-code generated and loaded (${gcode.length} lines, ${shape}).\nUse start_job to execute.\n\nPreview:\n${gcodeStr}`);
        }
        return text(`Pocket G-code generated (${gcode.length} lines):\n\n${gcodeStr}`);
      } catch (e: any) {
        return err(e.message);
      }
    }
  );

  // ── generate_gcode_drill ──────────────────────────────────

  server.tool(
    "generate_gcode_drill",
    "Generate G-code for drilling patterns (grid, circle, or custom points). Supports peck drilling.",
    {
      pattern: z.enum(["grid", "circle", "custom"]).describe("Drill pattern type"),
      centerX: z.number().default(0).describe("Pattern center X (mm)"),
      centerY: z.number().default(0).describe("Pattern center Y (mm)"),
      gridSpacingX: z.number().positive().optional().describe("Grid X spacing (mm)"),
      gridSpacingY: z.number().positive().optional().describe("Grid Y spacing (mm)"),
      gridCountX: z.number().int().positive().optional().describe("Number of holes in X direction"),
      gridCountY: z.number().int().positive().optional().describe("Number of holes in Y direction"),
      circleRadius: z.number().positive().optional().describe("Circle pattern radius (mm)"),
      holeCount: z.number().int().positive().optional().describe("Number of holes in circle pattern"),
      points: z.array(z.tuple([z.number(), z.number()])).optional().describe("Custom drill points as [x,y] pairs"),
      depth: z.number().positive().describe("Total drill depth (mm)"),
      peckDepth: z.number().positive().optional().describe("Peck depth per cycle (mm). If omitted, drills in one pass."),
      feedrate: z.number().positive().describe("Drilling feed rate (mm/min)"),
      spindleSpeed: z.number().positive().describe("Spindle speed (RPM)"),
      autoLoad: z.boolean().default(true).describe("Automatically load into CNCjs (default true)"),
    },
    async (params) => {
      try {
        const { pattern, centerX, centerY, depth, peckDepth, feedrate, spindleSpeed, autoLoad } = params;

        // Determine drill points
        let drillPts: [number, number][] = [];

        if (pattern === "grid") {
          if (!params.gridSpacingX || !params.gridSpacingY || !params.gridCountX || !params.gridCountY) {
            return err("Grid pattern requires gridSpacingX, gridSpacingY, gridCountX, gridCountY.");
          }
          const totalW = (params.gridCountX - 1) * params.gridSpacingX;
          const totalH = (params.gridCountY - 1) * params.gridSpacingY;
          for (let iy = 0; iy < params.gridCountY; iy++) {
            for (let ix = 0; ix < params.gridCountX; ix++) {
              drillPts.push([
                centerX - totalW / 2 + ix * params.gridSpacingX,
                centerY - totalH / 2 + iy * params.gridSpacingY,
              ]);
            }
          }
        } else if (pattern === "circle") {
          if (!params.circleRadius || !params.holeCount) {
            return err("Circle pattern requires circleRadius and holeCount.");
          }
          for (let i = 0; i < params.holeCount; i++) {
            const angle = (2 * Math.PI * i) / params.holeCount;
            drillPts.push([
              centerX + params.circleRadius * Math.cos(angle),
              centerY + params.circleRadius * Math.sin(angle),
            ]);
          }
        } else {
          if (!params.points || params.points.length < 1) return err("At least 1 point required for custom drill pattern.");
          drillPts = params.points as [number, number][];
        }

        const gcode: string[] = [...gcodeHeader(spindleSpeed)];

        for (const [x, y] of drillPts) {
          gcode.push(`G0 X${x.toFixed(3)} Y${y.toFixed(3)}`);
          gcode.push(`G0 Z1 ; Approach`);

          if (peckDepth) {
            // Peck drilling
            let drilled = 0;
            while (drilled < depth) {
              drilled = Math.min(drilled + peckDepth, depth);
              gcode.push(`G1 Z${(-drilled).toFixed(3)} F${feedrate}`);
              gcode.push(`G0 Z1 ; Retract for chip clearing`);
            }
          } else {
            // Single plunge
            gcode.push(`G1 Z${(-depth).toFixed(3)} F${feedrate}`);
          }

          gcode.push(`G0 Z${SAFE_Z}`);
        }

        gcode.push(...gcodeFooter());
        const gcodeStr = gcode.join("\n");

        if (autoLoad) {
          const name = `drill_${pattern}_${Date.now()}.nc`;
          client.loadGcode(name, gcodeStr);
          return text(`Drill G-code generated and loaded (${drillPts.length} holes, ${gcode.length} lines).\nUse start_job to execute.\n\nPreview:\n${gcodeStr}`);
        }
        return text(`Drill G-code generated (${drillPts.length} holes, ${gcode.length} lines):\n\n${gcodeStr}`);
      } catch (e: any) {
        return err(e.message);
      }
    }
  );

  // ── generate_gcode_facing ──────────────────────────────────

  server.tool(
    "generate_gcode_facing",
    "Generate G-code for surface facing/leveling. Raster pattern to flatten the work surface.",
    {
      width: z.number().positive().describe("Facing area width in X (mm)"),
      height: z.number().positive().describe("Facing area height in Y (mm)"),
      depth: z.number().positive().describe("Facing depth (mm) — typically 0.5-2mm"),
      stepOver: z.number().min(10).max(90).default(50).describe("Step-over as % of tool diameter (default 50%)"),
      feedrate: z.number().positive().describe("Cutting feed rate (mm/min)"),
      spindleSpeed: z.number().positive().describe("Spindle speed (RPM)"),
      toolDiameter: z.number().positive().describe("Tool diameter (mm)"),
      autoLoad: z.boolean().default(true).describe("Automatically load into CNCjs (default true)"),
    },
    async ({ width, height, depth, stepOver, feedrate, spindleSpeed, toolDiameter, autoLoad }) => {
      try {
        const stepOverDist = toolDiameter * (stepOver / 100);
        const gcode: string[] = [...gcodeHeader(spindleSpeed)];

        // Start from corner, raster across
        gcode.push(`G0 X0 Y0`);
        gcode.push(`G1 Z${(-depth).toFixed(3)} F${Math.round(feedrate / 3)} ; Plunge`);

        let y = 0;
        let leftToRight = true;
        while (y <= height) {
          if (leftToRight) {
            gcode.push(`G1 X${width.toFixed(3)} Y${y.toFixed(3)} F${feedrate}`);
          } else {
            gcode.push(`G1 X0 Y${y.toFixed(3)} F${feedrate}`);
          }
          y = Math.min(y + stepOverDist, height + 0.001);
          if (y <= height + 0.001) {
            gcode.push(`G1 Y${Math.min(y, height).toFixed(3)} F${feedrate}`);
          }
          leftToRight = !leftToRight;
        }

        gcode.push(...gcodeFooter());
        const gcodeStr = gcode.join("\n");

        if (autoLoad) {
          const name = `facing_${Date.now()}.nc`;
          client.loadGcode(name, gcodeStr);
          return text(`Facing G-code generated and loaded (${gcode.length} lines, ${width}x${height}mm).\nUse start_job to execute.\n\nPreview:\n${gcodeStr}`);
        }
        return text(`Facing G-code generated (${gcode.length} lines):\n\n${gcodeStr}`);
      } catch (e: any) {
        return err(e.message);
      }
    }
  );

  // ── generate_svg ──────────────────────────────────────────

  server.tool(
    "generate_svg",
    "Generate an SVG vector file for import into Carveco, Fusion 360, or other CAM software.",
    {
      shapes: z.array(z.object({
        type: z.enum(["circle", "rectangle", "line", "path"]).describe("Shape type"),
        cx: z.number().optional().describe("Center X (for circle/rectangle)"),
        cy: z.number().optional().describe("Center Y (for circle/rectangle)"),
        r: z.number().positive().optional().describe("Radius (for circle)"),
        width: z.number().positive().optional().describe("Width (for rectangle)"),
        height: z.number().positive().optional().describe("Height (for rectangle)"),
        x1: z.number().optional().describe("Start X (for line)"),
        y1: z.number().optional().describe("Start Y (for line)"),
        x2: z.number().optional().describe("End X (for line)"),
        y2: z.number().optional().describe("End Y (for line)"),
        d: z.string().optional().describe("SVG path data (for path type)"),
        stroke: z.string().default("black").describe("Stroke color (default black)"),
        strokeWidth: z.number().default(0.5).describe("Stroke width in mm (default 0.5)"),
        fill: z.string().default("none").describe("Fill color (default none)"),
      })).describe("Array of shapes to include in the SVG"),
      canvasWidth: z.number().positive().describe("Canvas width in mm"),
      canvasHeight: z.number().positive().describe("Canvas height in mm"),
      outputPath: z.string().describe("File path to save the SVG"),
    },
    async ({ shapes, canvasWidth, canvasHeight, outputPath }) => {
      try {
        let svgContent = `<?xml version="1.0" encoding="UTF-8"?>\n`;
        svgContent += `<svg xmlns="http://www.w3.org/2000/svg" width="${canvasWidth}mm" height="${canvasHeight}mm" viewBox="0 0 ${canvasWidth} ${canvasHeight}">\n`;

        for (const shape of shapes) {
          switch (shape.type) {
            case "circle":
              if (shape.cx === undefined || shape.cy === undefined || !shape.r) break;
              svgContent += `  <circle cx="${shape.cx}" cy="${shape.cy}" r="${shape.r}" stroke="${shape.stroke}" stroke-width="${shape.strokeWidth}" fill="${shape.fill}" />\n`;
              break;
            case "rectangle":
              if (shape.cx === undefined || shape.cy === undefined || !shape.width || !shape.height) break;
              svgContent += `  <rect x="${shape.cx - shape.width / 2}" y="${shape.cy - shape.height / 2}" width="${shape.width}" height="${shape.height}" stroke="${shape.stroke}" stroke-width="${shape.strokeWidth}" fill="${shape.fill}" />\n`;
              break;
            case "line":
              if (shape.x1 === undefined || shape.y1 === undefined || shape.x2 === undefined || shape.y2 === undefined) break;
              svgContent += `  <line x1="${shape.x1}" y1="${shape.y1}" x2="${shape.x2}" y2="${shape.y2}" stroke="${shape.stroke}" stroke-width="${shape.strokeWidth}" />\n`;
              break;
            case "path":
              if (!shape.d) break;
              svgContent += `  <path d="${shape.d}" stroke="${shape.stroke}" stroke-width="${shape.strokeWidth}" fill="${shape.fill}" />\n`;
              break;
          }
        }

        svgContent += `</svg>\n`;

        writeFileSync(outputPath, svgContent, "utf-8");
        return text(`SVG file saved to ${outputPath} (${canvasWidth}x${canvasHeight}mm, ${shapes.length} shapes).\n\nContent:\n${svgContent}`);
      } catch (e: any) {
        return err(e.message);
      }
    }
  );

  // ── generate_dxf ──────────────────────────────────────────

  server.tool(
    "generate_dxf",
    "Generate a DXF R12 file for import into CAM software (Carveco, Fusion 360, etc.). Dimensions in mm.",
    {
      entities: z.array(z.object({
        type: z.enum(["line", "circle", "arc", "polyline"]).describe("Entity type"),
        x1: z.number().optional().describe("Start X / Center X (for circle/arc)"),
        y1: z.number().optional().describe("Start Y / Center Y (for circle/arc)"),
        x2: z.number().optional().describe("End X (for line)"),
        y2: z.number().optional().describe("End Y (for line)"),
        radius: z.number().positive().optional().describe("Radius (for circle/arc)"),
        startAngle: z.number().optional().describe("Start angle in degrees (for arc)"),
        endAngle: z.number().optional().describe("End angle in degrees (for arc)"),
        points: z.array(z.tuple([z.number(), z.number()])).optional().describe("Points for polyline as [x,y] pairs"),
        closed: z.boolean().default(false).describe("Close the polyline (default false)"),
      })).describe("Array of DXF entities"),
      outputPath: z.string().describe("File path to save the DXF"),
    },
    async ({ entities, outputPath }) => {
      try {
        // DXF R12 minimal format
        let dxf = "";
        dxf += "0\nSECTION\n2\nHEADER\n";
        dxf += "9\n$INSUNITS\n70\n4\n"; // mm
        dxf += "0\nENDSEC\n";
        dxf += "0\nSECTION\n2\nENTITIES\n";

        for (const ent of entities) {
          switch (ent.type) {
            case "line":
              if (ent.x1 === undefined || ent.y1 === undefined || ent.x2 === undefined || ent.y2 === undefined) break;
              dxf += `0\nLINE\n8\n0\n10\n${ent.x1}\n20\n${ent.y1}\n30\n0\n11\n${ent.x2}\n21\n${ent.y2}\n31\n0\n`;
              break;
            case "circle":
              if (ent.x1 === undefined || ent.y1 === undefined || !ent.radius) break;
              dxf += `0\nCIRCLE\n8\n0\n10\n${ent.x1}\n20\n${ent.y1}\n30\n0\n40\n${ent.radius}\n`;
              break;
            case "arc":
              if (ent.x1 === undefined || ent.y1 === undefined || !ent.radius || ent.startAngle === undefined || ent.endAngle === undefined) break;
              dxf += `0\nARC\n8\n0\n10\n${ent.x1}\n20\n${ent.y1}\n30\n0\n40\n${ent.radius}\n50\n${ent.startAngle}\n51\n${ent.endAngle}\n`;
              break;
            case "polyline":
              if (!ent.points || ent.points.length < 2) break;
              dxf += `0\nPOLYLINE\n8\n0\n66\n1\n70\n${ent.closed ? 1 : 0}\n`;
              for (const [x, y] of ent.points) {
                dxf += `0\nVERTEX\n8\n0\n10\n${x}\n20\n${y}\n30\n0\n`;
              }
              dxf += `0\nSEQEND\n`;
              break;
          }
        }

        dxf += "0\nENDSEC\n0\nEOF\n";

        writeFileSync(outputPath, dxf, "utf-8");
        return text(`DXF file saved to ${outputPath} (${entities.length} entities, DXF R12 format).\nReady for import into Carveco, Fusion 360, or other CAM software.`);
      } catch (e: any) {
        return err(e.message);
      }
    }
  );
}
