// FreeCAD integration tools — generates Python scripts for headless FreeCAD CAD+CAM

import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { z } from "zod";
import { writeFileSync, readdirSync, statSync, readFileSync } from "fs";
import { join, resolve } from "path";

function text(s: string) {
  return { content: [{ type: "text" as const, text: s }] };
}

function json(obj: unknown) {
  return text(JSON.stringify(obj, null, 2));
}

function err(s: string) {
  return { content: [{ type: "text" as const, text: s }], isError: true };
}

// ── FreeCAD script templates ──────────────────────────────

function freecadHeader(headless: boolean): string {
  if (headless) {
    return `#!/usr/bin/env python3
# Generated by cncjs-mcp for FreeCAD (headless mode)
# Run with: freecadcmd <script.py>  OR  FreeCADCmd <script.py>

import sys
sys.path.append("/usr/lib/freecad/lib")  # Adjust if FreeCAD is installed elsewhere

import FreeCAD as App
import Part
import Path

doc = App.newDocument("Generated")
`;
  }
  return `#!/usr/bin/env python3
# Generated by cncjs-mcp for FreeCAD
# Run inside FreeCAD's Python console, or via: freecadcmd <script.py>

import FreeCAD as App
import FreeCADGui as Gui
import Part
import Path

doc = App.ActiveDocument or App.newDocument("Generated")
`;
}

function freecadFooter(outputPath?: string): string {
  let footer = "\ndoc.recompute()\n";
  if (outputPath) {
    const ext = outputPath.split(".").pop()?.toLowerCase();
    if (ext === "step" || ext === "stp") {
      footer += `\nPart.export(doc.Objects, "${outputPath.replace(/\\/g, "/")}")\n`;
      footer += `print("Exported STEP to ${outputPath.replace(/\\/g, "/")}")\n`;
    } else if (ext === "stl") {
      footer += `\nimport Mesh\nobjs = [o for o in doc.Objects if hasattr(o, "Shape")]\n`;
      footer += `Mesh.export(objs, "${outputPath.replace(/\\/g, "/")}")\n`;
      footer += `print("Exported STL to ${outputPath.replace(/\\/g, "/")}")\n`;
    } else if (ext === "fcstd") {
      footer += `\ndoc.saveAs("${outputPath.replace(/\\/g, "/")}")\n`;
      footer += `print("Saved FreeCAD file to ${outputPath.replace(/\\/g, "/")}")\n`;
    }
  }
  footer += `\nprint("Script completed successfully.")\n`;
  return footer;
}

export function registerFreeCADTools(server: McpServer): void {
  // ── generate_freecad_model ──────────────────────────────

  server.tool(
    "generate_freecad_model",
    "Generate a FreeCAD Python script to create a 3D model. Can run headless via freecadcmd for automated CAD.",
    {
      operations: z.array(z.object({
        type: z.enum([
          "box", "cylinder", "sphere", "cone",
          "sketch_rect", "sketch_circle", "sketch_polygon",
          "extrude", "pocket", "revolve",
          "fillet", "chamfer",
          "boolean_union", "boolean_cut", "boolean_intersect",
        ]).describe("Operation type"),
        // Primitive dimensions
        length: z.number().positive().optional().describe("Length/Width (mm) for box"),
        width: z.number().positive().optional().describe("Width/Depth (mm) for box"),
        height: z.number().positive().optional().describe("Height (mm) for box/extrude/pocket"),
        radius: z.number().positive().optional().describe("Radius (mm) for cylinder/sphere/cone/circle/fillet/chamfer"),
        radius2: z.number().optional().describe("Top radius for cone (0 for pointed)"),
        sides: z.number().int().min(3).optional().describe("Number of sides for polygon"),
        // Positioning
        x: z.number().default(0).describe("X position (mm)"),
        y: z.number().default(0).describe("Y position (mm)"),
        z: z.number().default(0).describe("Z position (mm)"),
        // Revolve
        angle: z.number().optional().describe("Revolve angle (degrees, default 360)"),
        axis: z.enum(["X", "Y", "Z"]).optional().describe("Revolve/extrude axis"),
        // Boolean
        target: z.string().optional().describe("Target body name for boolean ops"),
        tool: z.string().optional().describe("Tool body name for boolean ops"),
        // Naming
        name: z.string().optional().describe("Name for the created object"),
      })).min(1).describe("Sequence of modeling operations"),
      exportPath: z.string().optional().describe("Export path (.step, .stl, or .fcstd)"),
      outputScript: z.string().describe("File path to save the .py script"),
      headless: z.boolean().default(true).describe("Generate for headless execution (freecadcmd) — default true"),
    },
    async ({ operations, exportPath, outputScript, headless }) => {
      try {
        const lines: string[] = [freecadHeader(headless)];
        let objIndex = 0;

        for (const op of operations) {
          const name = op.name || `obj_${objIndex++}`;

          switch (op.type) {
            case "box": {
              const l = op.length || 100;
              const w = op.width || 100;
              const h = op.height || 10;
              lines.push(`# Create box: ${l}x${w}x${h}mm`);
              lines.push(`${name} = doc.addObject("Part::Box", "${name}")`);
              lines.push(`${name}.Length = ${l}`);
              lines.push(`${name}.Width = ${w}`);
              lines.push(`${name}.Height = ${h}`);
              lines.push(`${name}.Placement.Base = App.Vector(${op.x}, ${op.y}, ${op.z})`);
              lines.push("");
              break;
            }
            case "cylinder": {
              const r = op.radius || 25;
              const h = op.height || 50;
              lines.push(`# Create cylinder: r=${r}mm, h=${h}mm`);
              lines.push(`${name} = doc.addObject("Part::Cylinder", "${name}")`);
              lines.push(`${name}.Radius = ${r}`);
              lines.push(`${name}.Height = ${h}`);
              lines.push(`${name}.Placement.Base = App.Vector(${op.x}, ${op.y}, ${op.z})`);
              lines.push("");
              break;
            }
            case "sphere": {
              const r = op.radius || 25;
              lines.push(`# Create sphere: r=${r}mm`);
              lines.push(`${name} = doc.addObject("Part::Sphere", "${name}")`);
              lines.push(`${name}.Radius = ${r}`);
              lines.push(`${name}.Placement.Base = App.Vector(${op.x}, ${op.y}, ${op.z})`);
              lines.push("");
              break;
            }
            case "cone": {
              const r1 = op.radius || 25;
              const r2 = op.radius2 ?? 0;
              const h = op.height || 50;
              lines.push(`# Create cone: r1=${r1}mm, r2=${r2}mm, h=${h}mm`);
              lines.push(`${name} = doc.addObject("Part::Cone", "${name}")`);
              lines.push(`${name}.Radius1 = ${r1}`);
              lines.push(`${name}.Radius2 = ${r2}`);
              lines.push(`${name}.Height = ${h}`);
              lines.push(`${name}.Placement.Base = App.Vector(${op.x}, ${op.y}, ${op.z})`);
              lines.push("");
              break;
            }
            case "sketch_rect": {
              const l = op.length || 100;
              const w = op.width || 50;
              lines.push(`# Sketch rectangle: ${l}x${w}mm`);
              lines.push(`${name} = doc.addObject("Sketcher::SketchObject", "${name}")`);
              lines.push(`${name}.Placement = App.Placement(App.Vector(${op.x}, ${op.y}, ${op.z}), App.Rotation())`);
              lines.push(`geoList = []`);
              lines.push(`geoList.append(Part.LineSegment(App.Vector(0, 0, 0), App.Vector(${l}, 0, 0)))`);
              lines.push(`geoList.append(Part.LineSegment(App.Vector(${l}, 0, 0), App.Vector(${l}, ${w}, 0)))`);
              lines.push(`geoList.append(Part.LineSegment(App.Vector(${l}, ${w}, 0), App.Vector(0, ${w}, 0)))`);
              lines.push(`geoList.append(Part.LineSegment(App.Vector(0, ${w}, 0), App.Vector(0, 0, 0)))`);
              lines.push(`${name}.addGeometry(geoList, False)`);
              lines.push("");
              break;
            }
            case "sketch_circle": {
              const r = op.radius || 25;
              lines.push(`# Sketch circle: r=${r}mm`);
              lines.push(`${name} = doc.addObject("Sketcher::SketchObject", "${name}")`);
              lines.push(`${name}.Placement = App.Placement(App.Vector(${op.x}, ${op.y}, ${op.z}), App.Rotation())`);
              lines.push(`${name}.addGeometry(Part.Circle(App.Vector(0, 0, 0), App.Vector(0, 0, 1), ${r}), False)`);
              lines.push("");
              break;
            }
            case "sketch_polygon": {
              const r = op.radius || 25;
              const sides = op.sides || 6;
              lines.push(`# Sketch polygon: ${sides} sides, r=${r}mm`);
              lines.push(`import math`);
              lines.push(`${name} = doc.addObject("Sketcher::SketchObject", "${name}")`);
              lines.push(`${name}.Placement = App.Placement(App.Vector(${op.x}, ${op.y}, ${op.z}), App.Rotation())`);
              lines.push(`geoList = []`);
              lines.push(`for i in range(${sides}):`);
              lines.push(`    a1 = 2 * math.pi * i / ${sides}`);
              lines.push(`    a2 = 2 * math.pi * (i + 1) / ${sides}`);
              lines.push(`    geoList.append(Part.LineSegment(App.Vector(${r}*math.cos(a1), ${r}*math.sin(a1), 0), App.Vector(${r}*math.cos(a2), ${r}*math.sin(a2), 0)))`);
              lines.push(`${name}.addGeometry(geoList, False)`);
              lines.push("");
              break;
            }
            case "extrude": {
              const h = op.height || 10;
              lines.push(`# Extrude last sketch by ${h}mm`);
              lines.push(`${name} = doc.addObject("Part::Extrusion", "${name}")`);
              lines.push(`${name}.Base = doc.Objects[-2]  # Last sketch`);
              lines.push(`${name}.Dir = App.Vector(0, 0, ${h})`);
              lines.push(`${name}.Solid = True`);
              lines.push("");
              break;
            }
            case "pocket": {
              const h = op.height || 5;
              lines.push(`# Pocket (cut) last sketch by ${h}mm`);
              lines.push(`${name} = doc.addObject("Part::Extrusion", "${name}")`);
              lines.push(`${name}.Base = doc.Objects[-2]  # Last sketch`);
              lines.push(`${name}.Dir = App.Vector(0, 0, ${-h})`);
              lines.push(`${name}.Solid = True`);
              lines.push("");
              break;
            }
            case "revolve": {
              const ang = op.angle || 360;
              const ax = op.axis || "Z";
              const axVec = ax === "X" ? "1,0,0" : ax === "Y" ? "0,1,0" : "0,0,1";
              lines.push(`# Revolve last sketch ${ang}° around ${ax} axis`);
              lines.push(`${name} = doc.addObject("Part::Revolution", "${name}")`);
              lines.push(`${name}.Source = doc.Objects[-2]  # Last sketch`);
              lines.push(`${name}.Axis = App.Vector(${axVec})`);
              lines.push(`${name}.Angle = ${ang}`);
              lines.push(`${name}.Solid = True`);
              lines.push("");
              break;
            }
            case "fillet": {
              const r = op.radius || 2;
              lines.push(`# Fillet all edges with radius ${r}mm`);
              lines.push(`body = [o for o in doc.Objects if hasattr(o, "Shape") and o.Shape.Edges][-1]`);
              lines.push(`${name} = doc.addObject("Part::Fillet", "${name}")`);
              lines.push(`${name}.Base = body`);
              lines.push(`edges = [(i+1, ${r}, ${r}) for i in range(len(body.Shape.Edges))]`);
              lines.push(`${name}.Shape = body.Shape.makeFillet(${r}, body.Shape.Edges)`);
              lines.push("");
              break;
            }
            case "chamfer": {
              const r = op.radius || 1;
              lines.push(`# Chamfer all edges with distance ${r}mm`);
              lines.push(`body = [o for o in doc.Objects if hasattr(o, "Shape") and o.Shape.Edges][-1]`);
              lines.push(`${name} = doc.addObject("Part::Chamfer", "${name}")`);
              lines.push(`${name}.Base = body`);
              lines.push(`${name}.Shape = body.Shape.makeChamfer(${r}, body.Shape.Edges)`);
              lines.push("");
              break;
            }
            case "boolean_union": {
              const target = op.target || "obj_0";
              const tool = op.tool || "obj_1";
              lines.push(`# Boolean union: ${target} + ${tool}`);
              lines.push(`${name} = doc.addObject("Part::Fuse", "${name}")`);
              lines.push(`${name}.Base = doc.getObject("${target}")`);
              lines.push(`${name}.Tool = doc.getObject("${tool}")`);
              lines.push("");
              break;
            }
            case "boolean_cut": {
              const target = op.target || "obj_0";
              const tool = op.tool || "obj_1";
              lines.push(`# Boolean cut: ${target} - ${tool}`);
              lines.push(`${name} = doc.addObject("Part::Cut", "${name}")`);
              lines.push(`${name}.Base = doc.getObject("${target}")`);
              lines.push(`${name}.Tool = doc.getObject("${tool}")`);
              lines.push("");
              break;
            }
            case "boolean_intersect": {
              const target = op.target || "obj_0";
              const tool = op.tool || "obj_1";
              lines.push(`# Boolean intersect: ${target} ∩ ${tool}`);
              lines.push(`${name} = doc.addObject("Part::Common", "${name}")`);
              lines.push(`${name}.Base = doc.getObject("${target}")`);
              lines.push(`${name}.Tool = doc.getObject("${tool}")`);
              lines.push("");
              break;
            }
          }
        }

        lines.push(freecadFooter(exportPath));
        const script = lines.join("\n");

        writeFileSync(outputScript, script, "utf-8");
        return text(
          `FreeCAD script saved to ${outputScript}\n` +
          `Operations: ${operations.map((o) => o.type).join(", ")}\n` +
          (exportPath ? `Export: ${exportPath}\n` : "") +
          `\nTo run headless: freecadcmd ${outputScript}\n` +
          `To run in FreeCAD GUI: open Python console → exec(open("${outputScript}").read())\n` +
          `\nScript:\n${script}`
        );
      } catch (e: any) {
        return err(e.message);
      }
    }
  );

  // ── generate_freecad_cam ──────────────────────────────────

  server.tool(
    "generate_freecad_cam",
    "Generate a FreeCAD Python script for CAM toolpath generation and G-code export. Creates toolpaths from existing or new geometry.",
    {
      inputFile: z.string().optional().describe("Path to existing FreeCAD/STEP/STL file to load (optional — omit to create geometry in-script)"),
      operations: z.array(z.object({
        type: z.enum(["profile", "pocket", "drill", "face", "adaptive", "engrave"]).describe("CAM operation type"),
        depth: z.number().positive().describe("Total cut depth (mm)"),
        stepDown: z.number().positive().describe("Step-down per pass (mm)"),
        toolDiameter: z.number().positive().describe("Tool diameter (mm)"),
        feedrate: z.number().positive().describe("Cutting feedrate (mm/min)"),
        spindleSpeed: z.number().positive().describe("Spindle speed (RPM)"),
        side: z.enum(["inside", "outside"]).default("outside").describe("Cut side for profile operations"),
      })).min(1).describe("CAM operations to generate"),
      postProcessor: z.enum(["grbl", "linuxcnc", "mach3", "generic"]).default("grbl").describe("G-code post-processor (default grbl)"),
      gcodeOutput: z.string().describe("File path for the exported G-code (.nc/.gcode)"),
      outputScript: z.string().describe("File path to save the .py script"),
    },
    async ({ inputFile, operations, postProcessor, gcodeOutput, outputScript }) => {
      try {
        const lines: string[] = [
          `#!/usr/bin/env python3`,
          `# Generated by cncjs-mcp — FreeCAD CAM script`,
          `# Run with: freecadcmd ${outputScript}`,
          ``,
          `import sys`,
          `sys.path.append("/usr/lib/freecad/lib")`,
          ``,
          `import FreeCAD as App`,
          `import Part`,
          `import Path`,
          ``,
        ];

        if (inputFile) {
          const ext = inputFile.split(".").pop()?.toLowerCase();
          if (ext === "fcstd") {
            lines.push(`doc = App.openDocument("${inputFile.replace(/\\/g, "/")}")`);
          } else if (ext === "step" || ext === "stp") {
            lines.push(`doc = App.newDocument("CAM")`);
            lines.push(`Part.insert("${inputFile.replace(/\\/g, "/")}", doc.Name)`);
          } else if (ext === "stl") {
            lines.push(`doc = App.newDocument("CAM")`);
            lines.push(`import Mesh`);
            lines.push(`Mesh.insert("${inputFile.replace(/\\/g, "/")}", doc.Name)`);
          } else {
            lines.push(`doc = App.newDocument("CAM")`);
            lines.push(`# Unsupported file format — load manually`);
          }
        } else {
          lines.push(`doc = App.newDocument("CAM")`);
        }

        lines.push(``);
        lines.push(`# ── CAM Setup ──────────────────────────────────`);
        lines.push(`try:`);
        lines.push(`    import PathScripts.PathJob as PathJob`);
        lines.push(`    import PathScripts.PathProfile as PathProfile`);
        lines.push(`    import PathScripts.PathPocket as PathPocket`);
        lines.push(`    import PathScripts.PathDrilling as PathDrilling`);
        lines.push(`    import PathScripts.PathFace as PathFace`);
        lines.push(`    import PathScripts.PathPost as PathPost`);
        lines.push(`    HAS_PATH = True`);
        lines.push(`except ImportError:`);
        lines.push(`    HAS_PATH = False`);
        lines.push(`    print("Warning: FreeCAD Path workbench not available.")`);
        lines.push(`    print("Generating manual G-code path instead.")`);
        lines.push(``);

        // Generate manual Path commands as fallback (always works)
        lines.push(`# ── G-code Generation ─────────────────────────`);
        lines.push(`commands = []`);
        lines.push(``);

        for (let i = 0; i < operations.length; i++) {
          const op = operations[i];
          lines.push(`# Operation ${i + 1}: ${op.type}`);
          lines.push(`# Tool: ${op.toolDiameter}mm, Feed: ${op.feedrate}mm/min, Spindle: ${op.spindleSpeed}RPM`);
          lines.push(`# Depth: ${op.depth}mm, Step-down: ${op.stepDown}mm`);
          lines.push(`commands.append(Path.Command("G21"))  # mm mode`);
          lines.push(`commands.append(Path.Command("G90"))  # absolute`);
          lines.push(`commands.append(Path.Command("M3", {"S": ${op.spindleSpeed}}))`);
          lines.push(`commands.append(Path.Command("G4", {"P": 2}))  # dwell for spindle`);
          lines.push(`commands.append(Path.Command("G0", {"Z": 5}))  # safe height`);
          lines.push(``);

          if (op.type === "face") {
            lines.push(`# Facing operation — raster pattern`);
            lines.push(`_depth = 0`);
            lines.push(`while _depth < ${op.depth}:`);
            lines.push(`    _depth = min(_depth + ${op.stepDown}, ${op.depth})`);
            lines.push(`    commands.append(Path.Command("G0", {"X": 0, "Y": 0}))`);
            lines.push(`    commands.append(Path.Command("G1", {"Z": -_depth, "F": ${Math.round(op.feedrate / 3)}}))`);
            lines.push(`    # Add raster lines based on stock dimensions`);
            lines.push(`    commands.append(Path.Command("G1", {"X": 100, "F": ${op.feedrate}}))`);
            lines.push(`    commands.append(Path.Command("G0", {"Z": 5}))`);
          } else {
            lines.push(`# ${op.type} — configure in FreeCAD Path workbench for complex geometry`);
            lines.push(`# Placeholder: rapid to start, plunge, cut`);
            lines.push(`_depth = 0`);
            lines.push(`while _depth < ${op.depth}:`);
            lines.push(`    _depth = min(_depth + ${op.stepDown}, ${op.depth})`);
            lines.push(`    commands.append(Path.Command("G1", {"Z": -_depth, "F": ${Math.round(op.feedrate / 3)}}))`);
            lines.push(`    commands.append(Path.Command("G0", {"Z": 5}))`);
          }
          lines.push(``);
        }

        lines.push(`commands.append(Path.Command("G0", {"Z": 25}))  # retract`);
        lines.push(`commands.append(Path.Command("M5"))  # spindle off`);
        lines.push(`commands.append(Path.Command("G0", {"X": 0, "Y": 0}))  # home XY`);
        lines.push(`commands.append(Path.Command("M2"))  # program end`);
        lines.push(``);
        lines.push(`# Build Path object`);
        lines.push(`p = Path.Path(commands)`);
        lines.push(`o = doc.addObject("Path::Feature", "Toolpath")`);
        lines.push(`o.Path = p`);
        lines.push(`doc.recompute()`);
        lines.push(``);

        // Post-process selection
        const ppMap: Record<string, string> = {
          grbl: "grbl",
          linuxcnc: "linuxcnc",
          mach3: "mach3_mach4",
          generic: "grbl",
        };

        lines.push(`# ── Export G-code ─────────────────────────────`);
        lines.push(`gcode = p.toGCode()`);
        lines.push(`with open("${gcodeOutput.replace(/\\/g, "/")}", "w") as f:`);
        lines.push(`    f.write("; Generated by cncjs-mcp via FreeCAD\\n")`);
        lines.push(`    f.write("; Post-processor: ${postProcessor}\\n")`);
        lines.push(`    f.write(gcode)`);
        lines.push(`print(f"G-code exported to ${gcodeOutput.replace(/\\/g, "/")}")`);
        lines.push(`print(f"Total commands: {len(commands)}")`);
        lines.push(``);

        const script = lines.join("\n");
        writeFileSync(outputScript, script, "utf-8");

        return text(
          `FreeCAD CAM script saved to ${outputScript}\n` +
          `Operations: ${operations.map((o) => `${o.type} (${o.toolDiameter}mm, ${o.depth}mm deep)`).join(", ")}\n` +
          `Post-processor: ${postProcessor}\n` +
          `G-code output: ${gcodeOutput}\n` +
          `\nTo run: freecadcmd ${outputScript}\n` +
          `\nScript:\n${script}`
        );
      } catch (e: any) {
        return err(e.message);
      }
    }
  );

  // ── list_freecad_scripts ──────────────────────────────────

  server.tool(
    "list_freecad_scripts",
    "List previously generated FreeCAD Python scripts in a directory.",
    {
      directory: z.string().default(".").describe("Directory to search (default: current directory)"),
    },
    async ({ directory }) => {
      try {
        const dir = resolve(directory);
        const files = readdirSync(dir)
          .filter((f: string) => f.endsWith(".py") || f.endsWith(".fcstd"))
          .map((f: string) => {
            const fullPath = join(dir, f);
            const stat = statSync(fullPath);
            return {
              name: f,
              path: fullPath,
              size: stat.size,
              modified: stat.mtime.toISOString(),
            };
          })
          .sort((a: { modified: string }, b: { modified: string }) => b.modified.localeCompare(a.modified));

        if (files.length === 0) return text(`No .py or .fcstd files found in ${dir}`);
        return json(files);
      } catch (e: any) {
        return err(e.message);
      }
    }
  );
}
