// Fusion 360 integration tools — generates Python API scripts for Fusion 360

import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { z } from "zod";
import { writeFileSync, readdirSync, statSync } from "fs";
import { join, resolve } from "path";

function text(s: string) {
  return { content: [{ type: "text" as const, text: s }] };
}

function json(obj: unknown) {
  return text(JSON.stringify(obj, null, 2));
}

function err(s: string) {
  return { content: [{ type: "text" as const, text: s }], isError: true };
}

// ── Script templates ──────────────────────────────────────

function fusionHeader(): string {
  return `# Generated by CNC-design-control-MCP for Fusion 360
# Run this script in Fusion 360: Scripts and Add-Ins > Scripts > Run

import adsk.core, adsk.fusion, traceback

def run(context):
    ui = None
    try:
        app = adsk.core.Application.get()
        ui = app.userInterface
        design = app.activeProduct
        rootComp = design.rootComponent
`;
}

function fusionFooter(description: string): string {
  return `
        ui.messageBox('Script completed: ${description.replace(/'/g, "\\'")}')
    except:
        if ui:
            ui.messageBox('Failed:\\n{}'.format(traceback.format_exc()))
`;
}

function indentBlock(code: string, indent: string = "        "): string {
  return code.split("\n").map((line) => (line.trim() ? indent + line : "")).join("\n");
}

export function registerFusion360Tools(server: McpServer): void {
  // ── generate_fusion_script ──────────────────────────────────

  server.tool(
    "generate_fusion_script",
    "Generate a Fusion 360 Python API script for CAD/CAM operations. Saves a .py file to run in Fusion 360's Scripts and Add-Ins dialog.",
    {
      operation: z.enum([
        "sketch_rectangle",
        "sketch_circle",
        "extrude",
        "revolve",
        "fillet",
        "chamfer",
        "export_stl",
        "export_dxf",
        "cam_setup",
        "custom",
      ]).describe("Operation type"),
      params: z.record(z.union([z.string(), z.number(), z.boolean()])).default({}).describe(
        "Operation parameters. Common keys:\n" +
        "  sketch_rectangle: width, height, centerX, centerY\n" +
        "  sketch_circle: radius, centerX, centerY\n" +
        "  extrude: distance, operation (new_body/join/cut/intersect)\n" +
        "  revolve: angle (degrees), axisX, axisY, axisZ\n" +
        "  fillet/chamfer: radius/distance, edgeIndex\n" +
        "  export_stl/export_dxf: outputPath\n" +
        "  cam_setup: toolDiameter, feedrate, spindleSpeed, depth\n" +
        "  custom: (use 'code' key with raw Python code)"
      ),
      outputPath: z.string().describe("File path to save the .py script"),
      description: z.string().default("Fusion 360 operation").describe("Description of what this script does"),
    },
    async ({ operation, params, outputPath, description }) => {
      try {
        let scriptBody = "";

        switch (operation) {
          case "sketch_rectangle": {
            const w = Number(params.width || 100);
            const h = Number(params.height || 50);
            const cx = Number(params.centerX || 0);
            const cy = Number(params.centerY || 0);
            scriptBody = `
# Create a new sketch on XY plane
sketches = rootComp.sketches
xyPlane = rootComp.xYConstructionPlane
sketch = sketches.add(xyPlane)

# Draw rectangle centered at (${cx}, ${cy}), ${w}x${h} mm
lines = sketch.sketchCurves.sketchLines
p1 = adsk.core.Point3D.create(${(cx - w/2) / 10}, ${(cy - h/2) / 10}, 0)
p2 = adsk.core.Point3D.create(${(cx + w/2) / 10}, ${(cy - h/2) / 10}, 0)
p3 = adsk.core.Point3D.create(${(cx + w/2) / 10}, ${(cy + h/2) / 10}, 0)
p4 = adsk.core.Point3D.create(${(cx - w/2) / 10}, ${(cy + h/2) / 10}, 0)
lines.addByTwoPoints(p1, p2)
lines.addByTwoPoints(p2, p3)
lines.addByTwoPoints(p3, p4)
lines.addByTwoPoints(p4, p1)
`;
            break;
          }
          case "sketch_circle": {
            const r = Number(params.radius || 25);
            const cx = Number(params.centerX || 0);
            const cy = Number(params.centerY || 0);
            scriptBody = `
# Create a new sketch on XY plane
sketches = rootComp.sketches
xyPlane = rootComp.xYConstructionPlane
sketch = sketches.add(xyPlane)

# Draw circle at (${cx}, ${cy}), radius ${r}mm
circles = sketch.sketchCurves.sketchCircles
center = adsk.core.Point3D.create(${cx / 10}, ${cy / 10}, 0)
circles.addByCenterRadius(center, ${r / 10})
`;
            break;
          }
          case "extrude": {
            const dist = Number(params.distance || 10);
            const op = String(params.operation || "new_body");
            const opMap: Record<string, string> = {
              new_body: "adsk.fusion.FeatureOperations.NewBodyFeatureOperation",
              join: "adsk.fusion.FeatureOperations.JoinFeatureOperation",
              cut: "adsk.fusion.FeatureOperations.CutFeatureOperation",
              intersect: "adsk.fusion.FeatureOperations.IntersectFeatureOperation",
            };
            scriptBody = `
# Extrude the last sketch profile
sketches = rootComp.sketches
if sketches.count == 0:
    ui.messageBox('No sketches found. Create a sketch first.')
    return

sketch = sketches.item(sketches.count - 1)
if sketch.profiles.count == 0:
    ui.messageBox('No closed profiles in sketch.')
    return

profile = sketch.profiles.item(0)
extrudes = rootComp.features.extrudeFeatures
extInput = extrudes.createInput(profile, ${opMap[op] || opMap.new_body})
distance = adsk.core.ValueInput.createByReal(${dist / 10})
extInput.setDistanceExtent(False, distance)
extrudes.add(extInput)
`;
            break;
          }
          case "revolve": {
            const angle = Number(params.angle || 360);
            scriptBody = `
# Revolve the last sketch profile around Y axis
sketches = rootComp.sketches
if sketches.count == 0:
    ui.messageBox('No sketches found.')
    return

sketch = sketches.item(sketches.count - 1)
if sketch.profiles.count == 0:
    ui.messageBox('No closed profiles in sketch.')
    return

profile = sketch.profiles.item(0)
revolves = rootComp.features.revolveFeatures

# Use Y axis as revolve axis
yAxis = rootComp.yConstructionAxis
revInput = revolves.createInput(profile, yAxis, adsk.fusion.FeatureOperations.NewBodyFeatureOperation)
angle = adsk.core.ValueInput.createByString('${angle} deg')
revInput.setAngleExtent(False, angle)
revolves.add(revInput)
`;
            break;
          }
          case "fillet": {
            const radius = Number(params.radius || 2);
            scriptBody = `
# Apply fillet to all edges of the first body
bodies = rootComp.bRepBodies
if bodies.count == 0:
    ui.messageBox('No bodies found.')
    return

body = bodies.item(0)
edges = body.edges
fillets = rootComp.features.filletFeatures
filletInput = fillets.createInput()
edgeCollection = adsk.core.ObjectCollection.create()
for i in range(edges.count):
    edgeCollection.add(edges.item(i))
filletInput.addConstantRadiusEdgeSet(edgeCollection, adsk.core.ValueInput.createByReal(${radius / 10}), True)
fillets.add(filletInput)
`;
            break;
          }
          case "chamfer": {
            const dist = Number(params.distance || 1);
            scriptBody = `
# Apply chamfer to all edges of the first body
bodies = rootComp.bRepBodies
if bodies.count == 0:
    ui.messageBox('No bodies found.')
    return

body = bodies.item(0)
edges = body.edges
chamfers = rootComp.features.chamferFeatures
edgeCollection = adsk.core.ObjectCollection.create()
for i in range(edges.count):
    edgeCollection.add(edges.item(i))
chamferInput = chamfers.createInput2()
chamferInput.chamferEdgeSets.addEqualDistanceChamferEdgeSet(edgeCollection, adsk.core.ValueInput.createByReal(${dist / 10}), True)
chamfers.add(chamferInput)
`;
            break;
          }
          case "export_stl": {
            const outPath = String(params.outputPath || "output.stl").replace(/\\/g, "/");
            scriptBody = `
# Export first body as STL
bodies = rootComp.bRepBodies
if bodies.count == 0:
    ui.messageBox('No bodies found.')
    return

body = bodies.item(0)
exportMgr = design.exportManager
stlOptions = exportMgr.createSTLExportOptions(body, '${outPath}')
stlOptions.meshRefinement = adsk.fusion.MeshRefinementSettings.MeshRefinementMedium
exportMgr.execute(stlOptions)
`;
            break;
          }
          case "export_dxf": {
            const outPath = String(params.outputPath || "output.dxf").replace(/\\/g, "/");
            scriptBody = `
# Export last sketch as DXF
sketches = rootComp.sketches
if sketches.count == 0:
    ui.messageBox('No sketches found.')
    return

sketch = sketches.item(sketches.count - 1)
sketch.saveAsDXF('${outPath}')
`;
            break;
          }
          case "cam_setup": {
            const toolDia = Number(params.toolDiameter || 6);
            const feed = Number(params.feedrate || 1000);
            const spindle = Number(params.spindleSpeed || 12000);
            const depth = Number(params.depth || 5);
            scriptBody = `
# Note: CAM setup requires Fusion 360 Manufacturing workspace
# This script sets up a basic 2D pocket operation
import adsk.cam

camProduct = app.activeProduct
if not isinstance(camProduct, adsk.cam.CAM):
    ui.messageBox('Please switch to the Manufacturing workspace first.')
    return

cam = camProduct
setups = cam.setups

# Create setup if none exists
if setups.count == 0:
    setupInput = cam.setups.createInput(adsk.cam.OperationTypes.MillingOperation)
    setup = cam.setups.add(setupInput)
else:
    setup = setups.item(0)

ui.messageBox('CAM setup created.\\nTool diameter: ${toolDia}mm\\nFeedrate: ${feed}mm/min\\nSpindle: ${spindle}RPM\\nDepth: ${depth}mm\\n\\nManually configure toolpaths in the Manufacturing workspace.')
`;
            break;
          }
          case "custom": {
            const code = String(params.code || "# Add your custom Fusion 360 Python code here\npass");
            scriptBody = "\n" + code + "\n";
            break;
          }
        }

        const script = fusionHeader() + indentBlock(scriptBody) + fusionFooter(description);

        writeFileSync(outputPath, script, "utf-8");
        return text(
          `Fusion 360 script saved to ${outputPath}\n` +
          `Operation: ${operation}\n` +
          `Description: ${description}\n\n` +
          `To run:\n` +
          `1. Open Fusion 360\n` +
          `2. Go to Utilities > Scripts and Add-Ins (Shift+S)\n` +
          `3. Click "+" to add script folder, or run from saved location\n` +
          `4. Select and run the script\n\n` +
          `Script preview:\n${script}`
        );
      } catch (e: any) {
        return err(e.message);
      }
    }
  );

  // ── list_fusion_scripts ──────────────────────────────────

  server.tool(
    "list_fusion_scripts",
    "List previously generated Fusion 360 Python scripts in a directory.",
    {
      directory: z.string().default(".").describe("Directory to search for .py scripts (default: current directory)"),
    },
    async ({ directory }) => {
      try {
        const dir = resolve(directory);
        const files = readdirSync(dir)
          .filter((f) => f.endsWith(".py"))
          .map((f) => {
            const fullPath = join(dir, f);
            const stat = statSync(fullPath);
            return {
              name: f,
              path: fullPath,
              size: stat.size,
              modified: stat.mtime.toISOString(),
            };
          })
          .sort((a, b) => b.modified.localeCompare(a.modified));

        if (files.length === 0) return text(`No .py files found in ${dir}`);
        return json(files);
      } catch (e: any) {
        return err(e.message);
      }
    }
  );
}
