// Adobe Illustrator integration — generates ExtendScript (.jsx) files for automation

import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { z } from "zod";
import { writeFileSync, readdirSync, statSync } from "fs";
import { join, resolve } from "path";

function text(s: string) {
  return { content: [{ type: "text" as const, text: s }] };
}

function json(obj: unknown) {
  return text(JSON.stringify(obj, null, 2));
}

function err(s: string) {
  return { content: [{ type: "text" as const, text: s }], isError: true };
}

// ── Illustrator ExtendScript helpers ──────────────────────

function jsxHeader(docWidth: number, docHeight: number, units: string = "mm"): string {
  const colorMode = "DocumentColorSpace.RGB";
  // Illustrator uses points internally (1mm ≈ 2.83465 pt)
  const scale = units === "mm" ? 2.83465 : (units === "inches" ? 72 : 1);
  return `// Generated by CNC-design-control-MCP for Adobe Illustrator
// Run via: File > Scripts > Other Script... (select this .jsx file)
// Or from command line: illustrator.exe -run <script.jsx>

#target illustrator

var mm = ${scale}; // conversion factor to points

// Create new document
var doc = app.documents.add(
    ${colorMode},
    ${docWidth} * mm,
    ${docHeight} * mm
);
var layer = doc.activeLayer;

`;
}

function jsxFooter(exportPath?: string): string {
  let footer = "\n// Refresh view\napp.redraw();\n";
  if (exportPath) {
    const ext = exportPath.split(".").pop()?.toLowerCase();
    if (ext === "svg") {
      footer += `
// Export as SVG
var svgFile = new File("${exportPath.replace(/\\/g, "/")}");
var svgOpts = new ExportOptionsSVG();
svgOpts.embedRasterImages = true;
svgOpts.fontSubsetting = SVGFontSubsetting.None;
doc.exportFile(svgFile, ExportType.SVG, svgOpts);
`;
    } else if (ext === "dxf") {
      footer += `
// Export as AutoCAD DXF
var dxfFile = new File("${exportPath.replace(/\\/g, "/")}");
var dxfOpts = new ExportOptionsAutoCAD();
dxfOpts.exportFileFormat = AutoCADExportFileFormat.DXF;
dxfOpts.version = AutoCADCompatibility.AutoCADRelease21;
doc.exportFile(dxfFile, ExportType.AUTOCAD, dxfOpts);
`;
    } else if (ext === "pdf") {
      footer += `
// Save as PDF
var pdfFile = new File("${exportPath.replace(/\\/g, "/")}");
var pdfOpts = new PDFSaveOptions();
pdfOpts.compatibility = PDFCompatibility.ACROBAT5;
doc.saveAs(pdfFile, pdfOpts);
`;
    } else if (ext === "ai") {
      footer += `
// Save as AI
var aiFile = new File("${exportPath.replace(/\\/g, "/")}");
doc.saveAs(aiFile);
`;
    } else if (ext === "eps") {
      footer += `
// Save as EPS
var epsFile = new File("${exportPath.replace(/\\/g, "/")}");
var epsOpts = new EPSSaveOptions();
doc.saveAs(epsFile, epsOpts);
`;
    }
  }
  footer += '\nalert("Script completed successfully.");\n';
  return footer;
}

// Color helper
function jsxColor(color: string): string {
  // Accept hex (#FF0000), named colors, or "none"
  if (color === "none") return "new NoColor()";
  const colorMap: Record<string, [number, number, number]> = {
    black: [0, 0, 0], white: [255, 255, 255], red: [255, 0, 0],
    green: [0, 128, 0], blue: [0, 0, 255], yellow: [255, 255, 0],
    orange: [255, 165, 0], purple: [128, 0, 128], cyan: [0, 255, 255],
    magenta: [255, 0, 255], gray: [128, 128, 128], grey: [128, 128, 128],
  };
  let r = 0, g = 0, b = 0;
  if (color.startsWith("#") && color.length === 7) {
    r = parseInt(color.slice(1, 3), 16);
    g = parseInt(color.slice(3, 5), 16);
    b = parseInt(color.slice(5, 7), 16);
  } else if (colorMap[color.toLowerCase()]) {
    [r, g, b] = colorMap[color.toLowerCase()];
  }
  return `makeRGB(${r}, ${g}, ${b})`;
}

export function registerIllustratorTools(server: McpServer): void {
  // ── generate_illustrator_script ──────────────────────────

  server.tool(
    "generate_illustrator_script",
    "Generate an Adobe Illustrator ExtendScript (.jsx) to create vector artwork for CNC. Supports shapes, text, paths, and export to SVG/DXF/PDF.",
    {
      shapes: z.array(z.object({
        type: z.enum([
          "rectangle", "rounded_rectangle", "circle", "ellipse",
          "polygon", "star", "line", "path", "text",
        ]).describe("Shape type"),
        // Position and dimensions (in mm)
        x: z.number().default(0).describe("X position (mm)"),
        y: z.number().default(0).describe("Y position (mm)"),
        width: z.number().positive().optional().describe("Width (mm) for rectangle/ellipse"),
        height: z.number().positive().optional().describe("Height (mm) for rectangle/ellipse"),
        radius: z.number().positive().optional().describe("Radius (mm) for circle/polygon/star/rounded corners"),
        innerRadius: z.number().positive().optional().describe("Inner radius for star (mm)"),
        sides: z.number().int().min(3).optional().describe("Number of sides for polygon/star"),
        // Line/path
        x2: z.number().optional().describe("End X for line (mm)"),
        y2: z.number().optional().describe("End Y for line (mm)"),
        pathData: z.array(z.tuple([z.number(), z.number()])).optional().describe("Path points as [x,y] pairs (mm)"),
        closed: z.boolean().default(false).describe("Close the path"),
        // Text
        contents: z.string().optional().describe("Text contents"),
        fontSize: z.number().positive().optional().describe("Font size in points"),
        fontName: z.string().optional().describe("Font name (e.g., 'Arial', 'Helvetica')"),
        // Style
        stroke: z.string().default("black").describe("Stroke color (hex or name)"),
        strokeWidth: z.number().default(0.5).describe("Stroke width (mm)"),
        fill: z.string().default("none").describe("Fill color (hex, name, or 'none')"),
        name: z.string().optional().describe("Layer/object name"),
      })).min(1).describe("Shapes to create"),
      canvasWidth: z.number().positive().default(200).describe("Document width (mm)"),
      canvasHeight: z.number().positive().default(200).describe("Document height (mm)"),
      exportPath: z.string().optional().describe("Export path (.svg, .dxf, .pdf, .eps, or .ai)"),
      outputScript: z.string().describe("File path to save the .jsx script"),
    },
    async ({ shapes, canvasWidth, canvasHeight, exportPath, outputScript }) => {
      try {
        const lines: string[] = [jsxHeader(canvasWidth, canvasHeight)];

        // Helper function for colors
        lines.push(`function makeRGB(r, g, b) {`);
        lines.push(`    var c = new RGBColor();`);
        lines.push(`    c.red = r; c.green = g; c.blue = b;`);
        lines.push(`    return c;`);
        lines.push(`}`);
        lines.push(``);

        for (let i = 0; i < shapes.length; i++) {
          const s = shapes[i];
          const varName = s.name || `shape_${i}`;
          const safeVar = varName.replace(/[^a-zA-Z0-9_]/g, "_");

          lines.push(`// Shape ${i + 1}: ${s.type}${s.name ? ` (${s.name})` : ""}`);

          switch (s.type) {
            case "rectangle": {
              const w = s.width || 50;
              const h = s.height || 30;
              lines.push(`var ${safeVar} = layer.pathItems.rectangle(${s.y} * mm + ${h} * mm, ${s.x} * mm, ${w} * mm, ${h} * mm);`);
              break;
            }
            case "rounded_rectangle": {
              const w = s.width || 50;
              const h = s.height || 30;
              const r = s.radius || 5;
              lines.push(`var ${safeVar} = layer.pathItems.roundedRectangle(${s.y} * mm + ${h} * mm, ${s.x} * mm, ${w} * mm, ${h} * mm, ${r} * mm, ${r} * mm);`);
              break;
            }
            case "circle": {
              const r = s.radius || 25;
              // Illustrator's ellipse takes top, left, width, height
              lines.push(`var ${safeVar} = layer.pathItems.ellipse((${s.y} + ${r}) * mm, (${s.x} - ${r}) * mm, ${r * 2} * mm, ${r * 2} * mm);`);
              break;
            }
            case "ellipse": {
              const w = s.width || 50;
              const h = s.height || 30;
              lines.push(`var ${safeVar} = layer.pathItems.ellipse((${s.y} + ${h / 2}) * mm, (${s.x} - ${w / 2}) * mm, ${w} * mm, ${h} * mm);`);
              break;
            }
            case "polygon": {
              const r = s.radius || 25;
              const sides = s.sides || 6;
              lines.push(`var ${safeVar} = layer.pathItems.polygon(${s.x} * mm, ${s.y} * mm, ${r} * mm, ${sides});`);
              break;
            }
            case "star": {
              const r = s.radius || 25;
              const ir = s.innerRadius || r * 0.4;
              const points = s.sides || 5;
              lines.push(`var ${safeVar} = layer.pathItems.star(${s.x} * mm, ${s.y} * mm, ${r} * mm, ${ir} * mm, ${points});`);
              break;
            }
            case "line": {
              const x2 = s.x2 ?? s.x + 50;
              const y2 = s.y2 ?? s.y;
              lines.push(`var ${safeVar} = layer.pathItems.add();`);
              lines.push(`${safeVar}.setEntirePath([[${s.x} * mm, ${s.y} * mm], [${x2} * mm, ${y2} * mm]]);`);
              break;
            }
            case "path": {
              if (!s.pathData || s.pathData.length < 2) {
                lines.push(`// Skipped path — need at least 2 points`);
                break;
              }
              lines.push(`var ${safeVar} = layer.pathItems.add();`);
              const pts = s.pathData.map(([px, py]) => `[${px} * mm, ${py} * mm]`).join(", ");
              lines.push(`${safeVar}.setEntirePath([${pts}]);`);
              if (s.closed) {
                lines.push(`${safeVar}.closed = true;`);
              }
              break;
            }
            case "text": {
              const content = (s.contents || "Text").replace(/"/g, '\\"');
              const fontSize = s.fontSize || 24;
              const fontName = s.fontName || "Arial";
              lines.push(`var ${safeVar} = layer.textFrames.add();`);
              lines.push(`${safeVar}.contents = "${content}";`);
              lines.push(`${safeVar}.position = [${s.x} * mm, ${s.y} * mm];`);
              lines.push(`${safeVar}.textRange.characterAttributes.size = ${fontSize};`);
              lines.push(`try { ${safeVar}.textRange.characterAttributes.textFont = app.textFonts.getByName("${fontName}"); } catch(e) {}`);
              // Text color
              if (s.fill !== "none") {
                lines.push(`${safeVar}.textRange.characterAttributes.fillColor = ${jsxColor(s.fill)};`);
              }
              lines.push(``);
              continue; // skip generic styling for text
            }
          }

          // Apply styling (text uses `continue` above, so only non-text reaches here)
          if (s.stroke !== "none") {
            lines.push(`${safeVar}.stroked = true;`);
            lines.push(`${safeVar}.strokeColor = ${jsxColor(s.stroke)};`);
            lines.push(`${safeVar}.strokeWidth = ${s.strokeWidth} * mm;`);
          } else {
            lines.push(`${safeVar}.stroked = false;`);
          }
          if (s.fill !== "none") {
            lines.push(`${safeVar}.filled = true;`);
            lines.push(`${safeVar}.fillColor = ${jsxColor(s.fill)};`);
          } else {
            lines.push(`${safeVar}.filled = false;`);
          }
          lines.push(``);
        }

        lines.push(jsxFooter(exportPath));
        const script = lines.join("\n");

        writeFileSync(outputScript, script, "utf-8");
        return text(
          `Illustrator script saved to ${outputScript}\n` +
          `Document: ${canvasWidth}x${canvasHeight}mm, ${shapes.length} shapes\n` +
          (exportPath ? `Export: ${exportPath}\n` : "") +
          `\nTo run:\n` +
          `1. Open Adobe Illustrator\n` +
          `2. File > Scripts > Other Script...\n` +
          `3. Select ${outputScript}\n` +
          `\nScript:\n${script}`
        );
      } catch (e: any) {
        return err(e.message);
      }
    }
  );

  // ── generate_illustrator_export_script ─────────────────

  server.tool(
    "generate_illustrator_export_script",
    "Generate an Illustrator ExtendScript to batch-export the current document to SVG, DXF, PDF, or EPS.",
    {
      format: z.enum(["svg", "dxf", "pdf", "eps"]).describe("Export format"),
      outputPath: z.string().describe("Export file path"),
      options: z.object({
        outlineText: z.boolean().default(true).describe("Convert text to outlines before export (default true — recommended for CNC)"),
        flattenLayers: z.boolean().default(false).describe("Flatten all layers before export"),
      }).default({}).describe("Export options"),
      outputScript: z.string().describe("File path to save the .jsx script"),
    },
    async ({ format, outputPath, options, outputScript }) => {
      try {
        const lines: string[] = [
          `// Generated by CNC-design-control-MCP — Illustrator batch export script`,
          `// Run via: File > Scripts > Other Script...`,
          ``,
          `#target illustrator`,
          ``,
          `if (app.documents.length === 0) {`,
          `    alert("No document is open. Open a document first.");`,
          `} else {`,
          `    var doc = app.activeDocument;`,
          ``,
        ];

        if (options.outlineText) {
          lines.push(`    // Convert all text to outlines (important for CNC/laser cutting)`);
          lines.push(`    for (var i = doc.textFrames.length - 1; i >= 0; i--) {`);
          lines.push(`        doc.textFrames[i].createOutline();`);
          lines.push(`    }`);
          lines.push(``);
        }

        if (options.flattenLayers) {
          lines.push(`    // Flatten layers`);
          lines.push(`    while (doc.layers.length > 1) {`);
          lines.push(`        doc.layers[doc.layers.length - 1].hasSelectedArtwork = true;`);
          lines.push(`    }`);
          lines.push(``);
        }

        const outFile = outputPath.replace(/\\/g, "/");

        switch (format) {
          case "svg":
            lines.push(`    var outFile = new File("${outFile}");`);
            lines.push(`    var opts = new ExportOptionsSVG();`);
            lines.push(`    opts.embedRasterImages = true;`);
            lines.push(`    opts.fontSubsetting = SVGFontSubsetting.None;`);
            lines.push(`    opts.coordinatePrecision = 3;`);
            lines.push(`    doc.exportFile(outFile, ExportType.SVG, opts);`);
            break;
          case "dxf":
            lines.push(`    var outFile = new File("${outFile}");`);
            lines.push(`    var opts = new ExportOptionsAutoCAD();`);
            lines.push(`    opts.exportFileFormat = AutoCADExportFileFormat.DXF;`);
            lines.push(`    opts.version = AutoCADCompatibility.AutoCADRelease21;`);
            lines.push(`    opts.scaleLineweights = true;`);
            lines.push(`    doc.exportFile(outFile, ExportType.AUTOCAD, opts);`);
            break;
          case "pdf":
            lines.push(`    var outFile = new File("${outFile}");`);
            lines.push(`    var opts = new PDFSaveOptions();`);
            lines.push(`    opts.compatibility = PDFCompatibility.ACROBAT5;`);
            lines.push(`    opts.preserveEditability = false;`);
            lines.push(`    doc.saveAs(outFile, opts);`);
            break;
          case "eps":
            lines.push(`    var outFile = new File("${outFile}");`);
            lines.push(`    var opts = new EPSSaveOptions();`);
            lines.push(`    opts.embedLinkedFiles = true;`);
            lines.push(`    doc.saveAs(outFile, opts);`);
            break;
        }

        lines.push(`    alert("Exported to ${outFile}");`);
        lines.push(`}`);

        const script = lines.join("\n");
        writeFileSync(outputScript, script, "utf-8");

        return text(
          `Illustrator export script saved to ${outputScript}\n` +
          `Format: ${format.toUpperCase()}\n` +
          `Output: ${outputPath}\n` +
          `Outline text: ${options.outlineText}\n` +
          `\nTo run: File > Scripts > Other Script... > select ${outputScript}\n` +
          `\nScript:\n${script}`
        );
      } catch (e: any) {
        return err(e.message);
      }
    }
  );

  // ── list_illustrator_scripts ──────────────────────────────

  server.tool(
    "list_illustrator_scripts",
    "List previously generated Illustrator ExtendScript (.jsx) files in a directory.",
    {
      directory: z.string().default(".").describe("Directory to search (default: current directory)"),
    },
    async ({ directory }) => {
      try {
        const dir = resolve(directory);
        const files = readdirSync(dir)
          .filter((f: string) => f.endsWith(".jsx") || f.endsWith(".js"))
          .map((f: string) => {
            const fullPath = join(dir, f);
            const stat = statSync(fullPath);
            return {
              name: f,
              path: fullPath,
              size: stat.size,
              modified: stat.mtime.toISOString(),
            };
          })
          .sort((a: { modified: string }, b: { modified: string }) => b.modified.localeCompare(a.modified));

        if (files.length === 0) return text(`No .jsx or .js files found in ${dir}`);
        return json(files);
      } catch (e: any) {
        return err(e.message);
      }
    }
  );
}
